### ISSUE TITLE
Return as Cents to allow custom formatting of currency 

### ISSUE THREAD

**Issue by lukepolo** [lukepolo/laracart#100]
Allow the output to be in cents to allow the end user to use their own custom logic for money formatting.

**Comment by lukepolo** [comment]
this is in v2

**Comment by basepack** [comment]
Hi @lukepolo 

May I go ahead and implement this and provide you with a pull request? Or is this still reserved for your specific implementation?

Maybe we can discuss your desired end result here?

**Comment by lukepolo** [comment]
I’m cool with that , just need to make sure it passes all tests

**Comment by lukepolo** [comment]
@basepack #243 Thanks!
