### ISSUE TITLE
Update item not working

### ISSUE THREAD

**Issue by didadan** [lukepolo/laracart#101]
Hi Lukepolo,

according to your documentation this should work:

        $matches = \LaraCart::find(['id' => 123]);
        foreach($matches as $item){
            \LaraCart::updateItem($item->getHash(), 'title', 'asdd23');
            // $item->title= 'asd';
        }

When I do a `print_r` of `\Laracart::getItems()` right after that I get the **right** result. But that just in the  same process. When I do the same afterwards with a different request, I get the old result. Also tried with $item->title with the same result.

Using 1.1.10 with standard settings. Is there any command I am missing to persist the update?
Thank you.

**Comment by lukepolo** [comment]
You can call \LaraCart::update(), but that seems to be bug and should be saved directly after you call updateItem. Will have to look to see whats wrong.

Also you should be able todo  

`item->title= 'asd'; `

Are you saying that one doens't seem to update either?

**Comment by didadan** [comment]
yes.

**Comment by lukepolo** [comment]
```
 /**
     * Updates an items attributes
     *
     * @param $itemHash
     * @param $key
     * @param $value
     *
     * @return CartItem
     *
     * @throws Exceptions\InvalidPrice
     * @throws Exceptions\InvalidQuantity
     */
    public function updateItem($itemHash, $key, $value)
    {
        if (empty($item = $this->getItem($itemHash)) === false) {
            $item->$key = $value;
        }
        $item->generateHash();
        $this->update();
        return $item;
    }
```

Should update appropriately. Your not doing a dd or a dump on the page are you? dd for testing this are you ? If so it will not write to sessions when you do that.

**Comment by lukepolo** [comment]
I will test this out ASAP, thanks for brining it to my attention.

**Comment by didadan** [comment]
Hi Luke, I solved it.

After looking at your code - _I like the cleanliness and comments, wish everybody would code like that_ - I found that there are new configuration options which I didn't publish. `cross_devices` broke my neck here. Mainly my mistake, an isset would circumvent this but then I should be smarter.

Thanks for your quick reply.

**Comment by lukepolo** [comment]
Ill add that check! Thanks for debugging , feel free to make any PR's as well~

**Comment by lukepolo** [comment]
I made the fix for other config options, but not for cross devices, the default value should come into check and provide false. So not sure why that would cause issues.
