### ISSUE TITLE
Coupons not clear how to use

### ISSUE THREAD

**Issue by Cannonb4ll** [lukepolo/laracart#107]
It might be me, but im unsure how to use this exactly.

    $coupon = new \LukePOLO\LaraCart\Coupons\Fixed($coupon->CouponCode, $coupon->CouponValue, [
        'description' => $coupon->Description
    ]);

What do I enter @ $coupon->couponValue? Is this a percentage, a amount of the cart? I dont get it.

**Comment by aditya-cherukuri** [comment]
It's a value not a percentage. Example: 5.00, 10.99, etc.

**Comment by lukepolo** [comment]
Since its a "fixed" coupon  it means a fixed amount. So the copuon value would be like $ amount off. Ill have to add more doc to the included coupons. the percentage value would a % value

**Comment by lukepolo** [comment]
#117
