### ISSUE TITLE
Middleware can't get cart count

### ISSUE THREAD

**Issue by spaceageliving** [lukepolo/laracart#109]
Trying to implement a middleware that redirects to a controller/action based on cart qty.  For the handle method in the middleware, it seems that I am always getting a 0 count even with items in the cart.  Any idea why this would be?

    `public function handle($request, Closure $next)
    {
        if (LaraCart::count($withItemQty = false) == 0) {
            return redirect()->action('HomeController@index');
        }

        return $next($request);
    }`

...this redirect is always triggering, regardless of actual cart qty

**Comment by lukepolo** [comment]
The cart would not have been loaded yet since middleware happens in the middle :-). So to fix this just make sure to load the cart via : 



LaraCart::get($instance);


$instance can be null for default cart  



-- 
Luke Policinski
Sent with Airmail

On April 20, 2016 at 7:06:11 AM, spaceageliving (notifications@github.com) wrote:

lways triggering, regardless of actual cart

**Comment by lukepolo** [comment]
I probably can do a check before to make sure the cart has been loaded. ill make this an enhancement .

**Comment by spaceageliving** [comment]
Out of curiosity and for my edification, is the cart not loaded at this point (during middleware) because it gets instantiated via the service provider/app container, and that doesn't happen until later in the cycle?

**Comment by lukepolo** [comment]
That is correct.

**Comment by spaceageliving** [comment]
OK perfect....thanks for your insights (and work on this)...much appreciated!

**Comment by lukepolo** [comment]
No problem ill close this and make a note to look at a way to loading the cart if its not loading when calling a method. And as always feel free to request improvements, I am on vacation currently but when getting back I will be making some cool new features.

**Comment by spaceageliving** [comment]
Hmmm....still not getting correct result.  I'm trying this:

    `public function handle($request, Closure $next)
    {
        LaraCart::get();

        if (LaraCart::count($withItemQty = false) == 0) {
            return redirect()->action('HomeController@index');
        }

        return $next($request);
    }`
