### ISSUE TITLE
Middleware issue continues...

### ISSUE THREAD

**Issue by spaceageliving** [lukepolo/laracart#110]
Hmmm....still not getting correct result.  I'm trying this:

    `public function handle($request, Closure $next)
    {
        LaraCart::get();

        if (LaraCart::count($withItemQty = false) == 0) {
            return redirect()->action('HomeController@index');
        }

        return $next($request);
    }`

**Comment by lukepolo** [comment]
Try $cart = LaraCart::get();

$cart->count()

**Comment by spaceageliving** [comment]
Yeah I tried that previously, same result.

Wondering if this is due to the cart being dependent on the auth and session objects injected from DI container at instantiation?

**Comment by spaceageliving** [comment]
In the middleware, when I have:

`use LaraCart;`

the middleware doesn't work (per above), but no error is thrown.  I also tried:

`use \LukePOLO\LaraCart\LaraCart;`

and get:

ErrorException in NoCartItems.php line 19:
Non-static method LukePOLO\LaraCart\LaraCart::get() should not be called statically, assuming $this from incompatible context

line 19:

`$cart = LaraCart::get();`

**Comment by lukepolo** [comment]
When using facades its registered in the global space . Just do


Use LaraCart;

**Comment by spaceageliving** [comment]
Anyway, doesn't work for me with Use LaraCart...I resorted to putting the redirection test in the various controller actions and it is fine, just a lot of code duplication.  I originally went on this tact (middleware) after learning that the redirect helper doesn't work in a controller constructor.  Would like to learn what the issue is with the middleware usage at some point and implement that way.

**Comment by lukepolo** [comment]
When I get back (early may) I'll take a stab at it

**Comment by spaceageliving** [comment]
Cheers, have a good time!

**Comment by lukepolo** [comment]
Well , I tried reproducing but I can get the count no problem. 

`<?php

namespace App\Http\Middleware;

use Closure;

class LoadCart
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \Closure $next
     *
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        dd(\LaraCart::count()); // 1
        return $next($request);
    }
}`

**Comment by lukepolo** [comment]
Oh wait , are you using the cross browser functionality ?

**Comment by lukepolo** [comment]
"cross_devices"

**Comment by lukepolo** [comment]
Doesn't matter same result , i always get the count. What version of Laravel are you using and version of LaraCart?

**Comment by spaceageliving** [comment]
I'm noticing you have \LaraCart::count() (with slash), I don't think I was using the slash.  Could be a duh moment given the namespace of course.  I will take a closer look this am, thanks for getting back.

**Comment by lukepolo** [comment]
Yah I just didn't use a include at the top.

**Comment by lukepolo** [comment]
Facades are at a global namespace hence why that works.

**Comment by lukepolo** [comment]
Working fine for me, please supply me with your Laravel Version. 

I tested in 5.1 / 5.2 with PHP 7. 
Make sure your using the web middleware group or make sure your middleware is after 

\Illuminate\Session\Middleware\StartSession::class,

**Comment by spaceageliving** [comment]
Hi Luke--I got sucked into another client's project for the remainder of this week, will be working with your code this weekend for another project and will be giving this a go again then.  I'll let you know what I find.

**Comment by spaceageliving** [comment]
Hi Luke--I removed the use statement and just went with $cart = \LaraCart::get()...works fine.  I'm not sure what my issue was before to be honest, but I am getting success now with this change.

Thanks again for everything, you can close this one.

**Comment by lukepolo** [comment]
Awesome, what use statement did you have? Ill look into that issue as well

**Comment by spaceageliving** [comment]
use \LukePOLO\LaraCart\LaraCart;

**Comment by lukepolo** [comment]
Ah yes , that wont work :-) , next tiem just do

use LaraCart;
