### ISSUE TITLE
Model related

### ISSUE THREAD

**Issue by umbertix** [lukepolo/laracart#113]
First of all great job with this library looks brilliant.

So i'm having problems relating the model with the items for the cart.

//Config
    'item_model' => \App\Models\Model::class,
    'item_model_bindings' => [
        \LukePOLO\LaraCart\CartItem::ITEM_ID => 'stock_vendor_number',
        \LukePOLO\LaraCart\CartItem::ITEM_PRICE => 'price_pc',
        \LukePOLO\LaraCart\CartItem::ITEM_OPTIONS => []
    ],

//test controller
$item = LaraCart::add($diamond_id);
dd($item);

//Output
CartItem {#311 ▼
  #itemHash: "982822b0db28724a0911f76f96ddf53f"
  #itemModel: "App\Models\Model"
  #itemModelRelations: []
  +locale: null
  +taxable: true
  +lineItem: false
  +discount: 0
  +subItems: []
  +couponInfo: []
  +internationalFormat: null
  +options: array:5 [▼
    "id" => "14297"
    "qty" => 1
    "name" => null
    "price" => 0.0
    "tax" => null
  ]
}

I would expect the price to be the same as the model has. Am I missing something?

**Comment by lukepolo** [comment]
Yes it should! Blah! I'll look at this ASAP!

**Comment by lukepolo** [comment]
It seems the itemID works though correct?

**Comment by umbertix** [comment]
yeah, that's what is slighly confusing to me. But because the way that I'm creating the item is with an id, might be that it's not relating it at all and just taking the value that I pass.. ?

**Comment by umbertix** [comment]
My bad, as I said I was using and id instead of the object. Following the logic of the function I've realized about the problem.

You can tick it as resolved since there is no real problem. ;)

**Comment by lukepolo** [comment]
Awesome!

**Comment by lukepolo** [comment]
Would you like to pass it via ID as well ?

**Comment by umbertix** [comment]
Would be nice, at the moment what I'm doing is Model::find(id), and I just pass the model. 
I'd assumed that since the library 'knows' that it's expecting a default related model it would do it for me. It's not a big deal but would be a nice feature for me. Idk if other people would find it useful as well though.

**Comment by lukepolo** [comment]
What I can do is check to see if its an object of the model or an ID and look for that item

**Comment by umbertix** [comment]
Thinking a bit more about this, I think that the best option is to keep it as it is at the moment and just make it really obvious on the documentation. Otherwise in the case (probably a corner case) that you try to add an element with the same id as another that actually exist in your DB, with out you knowing, you might endup with the 'wrong' element? Not sure if that would ever happen, or if you can add an 'unrelated' item with just an id.
