### ISSUE TITLE
How to retrieve session cart?

### ISSUE THREAD

**Issue by umbertix** [lukepolo/laracart#114]
So my question is how do you retrieve the cart that is in session for the current user?

If i do 
`
 $tmp = Model::find($id);
LaraCart::add($tmp);
dd(LaraCart::getItems());
`

I get the items in the cart without a problem. But if I try to get `dd(LaraCart::getItems());` from enywherelse in my app it does not return anything.

**Comment by lukepolo** [comment]
LaraCart::get()

**Comment by lukepolo** [comment]
Ill add that to the docs today.

**Comment by umbertix** [comment]
I'm getting the same result.

If I make the call right after adding the elements the Cart returned is ok (with the items in it) but if I call it somewhere else there are no items in it. :(

**Comment by lukepolo** [comment]
Ok so when using 'dd' you must be very careful. When using the 'dd' function it will not write anything into the session. LaraCart uses the session to store its items. So to make sure your doing this right. Add the items to the cart. Then on the next request you can use dd to check whats inside.

**Comment by lukepolo** [comment]
Now if your adding things to the cart, then in the same request trying to use dd and thats not working we will have to debug further.

**Comment by umbertix** [comment]
Thx. Got it.
So, executing this:
`LaraCart::emptyCart();
 LaraCart::destroyCart();
$tmp = Model::find($id);
LaraCart::add($tmp);
dd(LaraCart::get());` would display a correct cart but it won't save it correctly in the session. So deleting the dd() does the trick. Therefore on the next call I can `dd(LaraCart::get());` and the Cart is correctly formed with all the info.

**Comment by lukepolo** [comment]
Perfect, we good then?
