### ISSUE TITLE
Dont allow taxable to accept non-integers 

### ISSUE THREAD

**Issue by umbertix** [lukepolo/laracart#116]
So it's more a question than a problem, I think.

Lets say that I have an item with a price of 10.000 and I want to apply a 20% tax on it.

If I leave the tax on settings to null so it applies the tax of each item.
```
//laracart.php
'tax' => null,
\LukePOLO\LaraCart\CartItem::ITEM_TAXABLE => 'tax',
```
(this is a protected variable inside the model with a fixed value, 0.2)

The result is:
```
subTotal: £10,000.00
totalDiscount: £0.00
taxTotal: £0.00
total: £10,000.00

    +taxable: 0.2
    +lineItem: false
    +discount: 0
    +subItems: []
    +couponInfo: []
    +internationalFormat: null
    +options: array:5 [▼
      "id" => 14704
      "qty" => 1
      "name" => null
      "price" => 10000.0
      "tax" => null
    ]
```
So as you can see the taxable has a value but it's not applying it, and aparently it does not apply the item value to it.

So let's try it the other way round. General tax and skip the item related.
```
'tax' => 0.2,
\LukePOLO\LaraCart\CartItem::ITEM_TAXABLE => 'null',
```
The result is:
```
subTotal: £10,000.00
totalDiscount: £0.00
taxTotal: £0.00
total: £10,000.00

 +taxable: null
    +lineItem: false
    +discount: 0
    +subItems: []
    +couponInfo: []
    +internationalFormat: null
    +options: array:5 [▼
      "id" => 14704
      "qty" => 1
      "name" => null
      "price" => 10000.0
      "tax" => 0.2
    ]
  }
```
Now it seems like the item has the tax but again it's not apllyint it.

Applying it to both:
```
'tax' => 0.2,
\LukePOLO\LaraCart\CartItem::ITEM_TAXABLE => 'tax',
```
```
subTotal: £10,000.00
totalDiscount: £0.00
taxTotal: £2,000.00
total: £12,000.00

    +taxable: 0.2
    +lineItem: false
    +discount: 0
    +subItems: []
    +couponInfo: []
    +internationalFormat: null
    +options: array:5 [▼
      "id" => 14704
      "qty" => 1
      "name" => null
      "price" => 10000.0
      "tax" => 0.2
    ]
  }
```
So if we apply the setting in both sides it does work. Is that the intended way to work? It does seems wrong to me. :|

**Comment by lukepolo** [comment]
taxable should be boolean, true or false. Probably why it didnt work.

**Comment by lukepolo** [comment]
ill have to make that more clear , and should't allow it

**Comment by lukepolo** [comment]
PR #117
