### ISSUE TITLE
Migration published && migrating error

### ISSUE THREAD

**Issue by Cannonb4ll** [lukepolo/laracart#119]
I was kind of suprised I got a migration from this package, then I realized it was actually a very good idea to save the cart to the user, I was bound to use it but I ran into some weird errors.

- Is there a reason you are giving the migration the year 2000 so it comes first in line? The default laravel user migration is from 2014-10-12 so if you try to add columns to that table, errors occur:

     Nothing to rollback.
     [Illuminate\Database\QueryException]
     SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voormeubels.users' doesn't exist (SQL: alter table `users` add `cart_session_id` varchar(255) not null)
    [PDOException]
    SQLSTATE[42S02]: Base table or view not found: 1146 Table 'voormeubels.users' doesn't exist

- Each time we do *php artisan vendor:publish --provider='LukePOLO\LaraCart\LaraCartServiceProvider'* it would publish/overwrite the migration, which is kinda weird.

Is it OK if I make a PR for this?

**Comment by Cannonb4ll** [comment]
See PR #120

**Comment by lukepolo** [comment]
Hey glad you did that PR, merged in, will publish soon. I just did some more upgrades and want to make sure everything is sound before making a release for it. Now for the first issue No there i not a reason for year 2000 , I forget why I did that. Ill go ahead and change that

**Comment by Cannonb4ll** [comment]
Awesome mate, this PR fixes both the issues I describe by the way :)

I'll be looking forward to your release & upgrade.

**Comment by lukepolo** [comment]
Oh oups thank you very much!

**Comment by lukepolo** [comment]
Released , should be stable.

**Comment by lukepolo** [comment]
Glad your using the cross device stuff I put in. Thought I was the only one!

**Comment by Cannonb4ll** [comment]
I am currently building a webshop for a customer of mine, and I had this package in the back of my mind :)

I will help wherever I can, also whenever I find bugs I will report them to you.
