### ISSUE TITLE
InvalidTaxableValue in CartOptionsMagicMethodsTrait.php line 61:

### ISSUE THREAD

**Issue by Cannonb4ll** [lukepolo/laracart#121]
Im not sure if this has anything to do with your latest release, but its currently breaking the complete package on version 1.1.18

Error that I am getting when trying to add a product to the cart (default code from docs generates the same error):

    InvalidTaxableValue in CartOptionsMagicMethodsTrait.php line 61:
    The tax must be a float less than 1

**Comment by lukepolo** [comment]
Hmmmm ill go remove that sorry.

**Comment by lukepolo** [comment]
Commented it out, 1.1.19 released. Will test that one more. All my tests passed which is odd should have failed.

**Comment by lukepolo** [comment]
fixed PR #124
