### ISSUE TITLE
itemModel Bind issues. 

### ISSUE THREAD

**Issue by alvaroenoht** [lukepolo/laracart#125]
In the last update 1.1.20 when using the model binding, the model wasnt loading in the constructor. 
The reason was in LaraCart.php line 219, 

I changed it to 
$itemModel = $itemModel->with($this->itemModelRelations)->find($itemID); 

and then line 238 taxable is expecting bool but Mysql wont return bool so I changed it to 
$taxable = $itemModel[$bindings[\LukePOLO\LaraCart\CartItem::ITEM_TAXABLE]]?true:false;

**Comment by lukepolo** [comment]
Can you make a PR changes seems solid enough

**Comment by lukepolo** [comment]
Thank you for the insights on this !

**Comment by lukepolo** [comment]
PR #126

**Comment by lukepolo** [comment]
https://github.com/lukepolo/laracart/commit/c45166e7dedeac4ceeed2a62a09e89c5b6f83559

**Comment by alvaroenoht** [comment]
No problem!. thank you for this code.
