### ISSUE TITLE
Discount per item

### ISSUE THREAD

**Issue by theerakit** [lukepolo/laracart#133]
Could you create function discount per item ? discount by cash many qty many discount, calculate at total per item and sum at total

**Comment by lukepolo** [comment]
You should create your own coupon class and include it  like this

   $coupon = new \LukePOLO\LaraCart\Coupons\Fixed($coupon->CouponCode, $coupon->CouponValue, [
        'description' => $coupon->Description
    ]);

    LaraCart::addCoupon($coupon);

Look at the code inside of that class and follow that and you should be golden .

**Comment by lukepolo** [comment]
Closing the issue, let me know if you need more help.
