### ISSUE TITLE
How to set the price with the tax already included (question)

### ISSUE THREAD

**Issue by jaumeavila** [lukepolo/laracart#135]
Hello,
I would like to bind the price of the item to the price of my model with the tax already included.
I have been able to bind bot price and tax ok, but the total price is the base price with the tax on top pf that.
And what I need is the price of my model to be calculated as the total price with the vat already added.

Thanks!

**Comment by lukepolo** [comment]
What I would do is just make tax = 0% , would that work ?

 Otherwise you can just always use LaraCart::total(false) and
$item->price($false) everywhere instead

**Comment by jaumeavila** [comment]
That would not work because then I cannot get any tax.
It is not that the product does not have any taxes, it is that the price set already has it and the subTotal should do the calculations taking that into account.
When my clients set a price to a product, most of the times it is the final price hehe

**Comment by lukepolo** [comment]
Gotcha , just make the iems non taxable (since its already included) by flagging it to false . Look at the API here
```
LaraCart::add(
        $itemID,
        $name = null,
        $qty = 1,
        $price = '0.00',
        $options = [],
        $taxable = true,
        $lineItem = false
    )
```

**Comment by lukepolo** [comment]
only problem then is you cannot use my method to get your taxes , you will have to write a helper for that.

**Comment by jaumeavila** [comment]
Yes, that is what I have done hehe

Thanks!
