### ISSUE TITLE
Questions re: coupons

### ISSUE THREAD

**Issue by spaceageliving** [lukepolo/laracart#136]
Hi Luke, I'm implementing coupons on my checkout code, have a few questions about usage.

It looks to me like I have to implement:

--the discount code checking (ie. if I have a discount code in effect in my checkout process, I have to do the comparison to determine if user has entered a valid value that I am honoring),

--the valid start date and end date, both of which would be used to determine if a code should be attached to the cart?

Then when these conditions are met, I would instantiate the appropriate coupon per my desired implementation and attach to the cart?

Is this accurate, or am I missing some aspect of the functionality?

TIA,
David

**Comment by lukepolo** [comment]
Actually, you can do this all within the coupon itself! Just pass what you need into the options array when constructing it.

```
   $options = [
         'start-date' => $startDate,   
         .....
   ]
```

What I actually do is pass in my coupon model like 

```
    // Where $couponModel is // App/Models/Coupon
    $coupon = new \LukePOLO\LaraCart\Coupons\Fixed($coupon->CouponCode, $coupon->CouponValue, $couponModel->toArray());

```

```
        public function __construct($code, $value, $options = [])
        {
            $this->code = $code;
            $this->value = $value / 100;

            $this->setOptions($options);
        }

        public function discount($throwErrors = false)
        {
             if($this->startDate > Carbon::Now()) {
                return \LaraCart::subTotal(false) * $this->value;
             }
            if($throwErrors) {
                 return throw new Exception('Invalid coupon, the date has passed');
           }

           return 0;
        }
````

**Comment by lukepolo** [comment]
Ill update the docs tonight to give more of a detailed view how the $throwErrors work along with a better example.

**Comment by spaceageliving** [comment]
Thanks again, I will give it a shot.

**Comment by lukepolo** [comment]
You know whats funny. When you have features you didn't remember coding 👍 , updated docs.

http://laracart.lukepolo.com/#coupon-helpers

**Comment by spaceageliving** [comment]
Wow great docs update, thanks!  I will be diving into coupons this week...

**Comment by lukepolo** [comment]
Going to close this for now~

**Comment by spaceageliving** [comment]
Hi Luke, I took a look over the docs, thanks for that additional info.

I'm still a little unclear about the usage.  I'm trying to implement a "discount code" entry as part of my checkout flow.  I can see how you set the code for the coupon when instantiating, but what would be the recommended way to "connect the dots" between the coupon/code value entered by the user and the coupon?  I'm envisioning there needs to be a step in the logic of my controller that compares the value the user has entered against a list of valid coupon codes, and then applying the coupon to the cart if one is found?  Curious how you envision this being implemented in practice...

Thanks,
David

**Comment by lukepolo** [comment]
How I would do it is , you would use the database to store the coupons with
a couple type (great thing to use with morphTo relationship) , validate it
in your controller then apply the coupon. Then you would validate if the
coupon is applied within the coupon class you have created .

Does that help?

**Comment by spaceageliving** [comment]
Yes, perfect and thanks again.  I wanted to be sure I wasn't missing something as far as code checking.  Have a great weekend!

**Comment by lukepolo** [comment]
No problem 😄, glad I could help , love working on this package when I have
time!

**Comment by spaceageliving** [comment]
OK everything is going great now, really happy.  I am able to apply a custom coupon, cart total updates accordingly.

One last issue: this will probably "never" happen, but in my checkout scenario, it is possible to remove a perviously entered discount code.  In this case, a code is still in effect in the cart, but since a valid code is no longer being provided by the user, I technically should remove any coupon from the cart.  But, I no longer have the coupon code (since user removed it from input).  I don't see a removeCoupons() method, and removeCoupon($code) requires you to know the code of the coupon you want removed...what would be best way to deal with this?  Get all coupons and remove each?

**Comment by spaceageliving** [comment]
...or I guess I could empty the cart->coupons array?

**Comment by aditya-cherukuri** [comment]
Yes.. you can do that. Or this if Luke agrees with this PR then that will help too 
https://github.com/lukepolo/laracart/pull/137

**Comment by lukepolo** [comment]
👍
