### ISSUE TITLE
Search for SubItems

### ISSUE THREAD

**Issue by airbase9018** [lukepolo/laracart#138]
Hi there, 

Is there a way where we can search for subItems of an Item? Seems that there is no function for this yet. 
I'm talking about finding for a specific subItem, by not using its hash.

Great package btw. :)

**Comment by aditya-cherukuri** [comment]
Currently there is no option to search for a subItem without using the hash. 
1. Are you trying to look for a subItem using it's name? 
2. Are you looking for this subItem within a particular item or if the subItem is part of any item in the cart.

**Comment by lukepolo** [comment]
I'll see if I can add this in this weekend. 


Glad you like the package! 2.0 is around the corner and will be changing some of the sub item stuff. As its quite confusing.

**Comment by airbase9018** [comment]
Hi aditya-cherukuri
Yeah I was trying to search for the subitem's options (name, id, custom field, etc).
The subitem is part of a particular Item. 
For now I'm just looping for all the subItems and check from there if that subItem did exist. :)

lukepolo

Do you have timeline for the 2.0? when can we expect it? this is a very simple carting system imho.

**Comment by lukepolo** [comment]
Just a snippet what Im going to complete 

 - Database Version (50%)
 - Shipping Fee Helper / Free Shipping Coupon (75%)
 - Money Format in cents (useful for stripe and other api payments) (80%)
 - Items can have Sub Items, and sub items can have sub items themselves (still thinking through this one) (0%)
 - Code Cleanup 

Estimated Release July 1st 👍

**Comment by lukepolo** [comment]
Hopefully its simple! I may change a few API terms as well. That wont be known till I get to the code clean up. I want to clean up the main LaraCart.php. Its getting big and theres a better way to make it still useful with better readability.

**Comment by lukepolo** [comment]
I plan on adding this this weekend , hopfully here in a few hours.

**Comment by lukepolo** [comment]
https://github.com/lukepolo/laracart/releases/tag/1.1.28
