### ISSUE TITLE
Item details are inserted into options.

### ISSUE THREAD

**Issue by obarlas** [lukepolo/laracart#149]
When I add a product to the cart, all the item details are inserted to the options value of the CartItem. There is a simple test script below;

`public function getTest()
{
        Cart::destroyCart();

        $item = Cart::add(14, "Product", 1, 100.23, ["Color" => "Black"]);

        dd($item, Cart::getItems());
}`

When I visit /cart the result is as follows;

`CartItem {#604 ▼
  #itemHash: "beafcd23ce64dfa541f9ebd8c8c2ec5b"
  #itemModel: null
  #itemModelRelations: []
  +locale: null
  +lineItem: false
  +discount: 0
  +subItems: []
  +couponInfo: []
  +internationalFormat: null
  +options: array:7 [▼
    "id" => 14
    "qty" => 1
    "name" => "Product"
    "taxable" => true
    "price" => 100.23
    "tax" => null
    "Color" => "Black"
  ]
}

array:1 [▼
  "beafcd23ce64dfa541f9ebd8c8c2ec5b" => CartItem {#604 ▼
    #itemHash: "beafcd23ce64dfa541f9ebd8c8c2ec5b"
    #itemModel: null
    #itemModelRelations: []
    +locale: null
    +lineItem: false
    +discount: 0
    +subItems: []
    +couponInfo: []
    +internationalFormat: null
    +options: array:7 [▼
      "id" => 14
      "qty" => 1
      "name" => "Product"
      "taxable" => true
      "price" => 100.23
      "tax" => null
      "Color" => "Black"
    ]
  }
]`

am I missing something here?

**Comment by lukepolo** [comment]
Its how the system works :-) , its working properly

**Comment by lukepolo** [comment]
It seems a bit stuipd, I agree, im not sure the reason I ended on that design pattern. Im sure ill look more into it in V2.

**Comment by lukepolo** [comment]
When you access the items you can still do $item->id , etc.
