### ISSUE TITLE
Eternal fee

### ISSUE THREAD

**Issue by umbertix** [lukepolo/laracart#150]
Hi, I just found a bit of a problem with the fess.

I was playing a bit with the addFee, functionality and at some point I'd decided to change the name of the fee. The problem comes here, since then I was seeing the fee even it wasn't on my code and I did tried restarting nginx, php, LaraCart::emptyCart() and LaraCart::destroyCart(). Nothing have affected it apart of removing the fee manually.

Not sure if I would consider it a bug or  just a think to have in consideration, since this changes where in my dev. environment is  not a big deal apart of the confusion of having fees that no longer are represented in the code, but thinking of it I see a problem if at any point you make a similar change and push it live. In that case the 'live' system would have the fees wrong, unless that you force it in a migration or manual process. 

Shouldn't the destroy method clear all the fees aswell? Or have you thought it in a different way?

Cheers.

**Comment by lukepolo** [comment]
That is definitely a bug, kinda. When you push it out make sure you clear the sessions with the old carts `php artisan cache:clear` . 

But the real bug is the empty and destroy cart should get rid of them. 

If you can write a test to reproduce this i should be able to fix it tonight. Otherwise it may have to wait for a couple of days till I can get around to it.

**Comment by umbertix** [comment]
While doing the test for it I've seen that I cannot replicate it on the system atm. It might be because I'm running the phpunit without being on a vagrant machine. I'll try to investigate it a bit more on the following days if I have a moment. In any case I'll leave you the 2 lines of code that I have added since they are real simple and might ease you if you want a give it a go aswell.

LaraCartTest.php
`    /**
     * Test destroying the cart rather than just emptying it.
     */
    public function testDestroyCart()
    {
        $this->addItem();

        $this->laracart->setAttribute('test', 1);
                             $this->laracart->addFee('test_fee', 10.50, true);

        $this->laracart->destroyCart();

        $this->assertEquals(null, $this->laracart->getAttribute('test'));
        $this->assertEquals(0, $this->laracart->count());
                             $this->assertEquals('$0.00', $this->laracart->getFee('test_fee')->getAmount());
    }`


Note that the two lines are the ones out of tabulation.

;)

**Comment by lukepolo** [comment]
Thanks ! I think I may have some time this week to get this fixed , along with docs available in a repo for the public

**Comment by umbertix** [comment]
I don't seem to be able to replicate the problem on the tests, so I'm starting to thing that is something with my dev environment. 

I have found that the problem (on my dev) only appears when I'm using the cross_device option activated. I have tried using redis or files for both cache and session drivers but with the same result.

**Comment by lukepolo** [comment]
Ok, so the way to replicate it on your dev machine is :  


1. Create a fee with "test"
2. Rename "test" to "test1"
3. Fee "test" is still in cart along with "test1" 

Is this what is happening ?

**Comment by umbertix** [comment]
Yes, that's exactly what is happening. If I deactivate the cross_device option it behaives normaly though,

**Comment by lukepolo** [comment]
Yup that makes sense. So the cross_device saves the cart as it is in the session. So it does not check to see if that fee should still exist. 

This is something you have to carful about , and I probably should write that in the docs to clear your old carts.

**Comment by umbertix** [comment]
I thought, that `$this->session->forget($this->prefix.'.'.$instance);` would clear the cart though.

**Comment by lukepolo** [comment]
Found the bug, new release coming ~
