### ISSUE TITLE
The cart subtotal appears to always add tax ignoring the line item tax boolean

### ISSUE THREAD

**Issue by sunscreem** [lukepolo/laracart#154]
In the main [laracart code](https://github.com/lukepolo/laracart/blob/master/src/LaraCart.php#L581) here the docs say:

```
/** Gets the total of the cart with or without tax.
```

But I can't see anything in the function that considers the line item taxable boolean?

**Comment by lukepolo** [comment]
The 3rd parameter should didctate that , that's for the entire cart

**Comment by sunscreem** [comment]
Sorry Luke - I linked to the wrong function. I meant to link to [this one](https://github.com/lukepolo/laracart/blob/master/src/LaraCart.php#L605).

I'll explain my problem again.

If I add 2 different items to a cart, one with tax and one has no tax, then the total for the basket works perfectly. 

However - the subtotal for the basket (before fees) always adds tax ignoring the taxable boolean.

**Comment by lukepolo** [comment]
Gotcha , hopping on now to fix !

**Comment by lukepolo** [comment]
Well subtotal should never have tax. so if its adding tax always we have a big problem!

**Comment by lukepolo** [comment]
$item = $this->addItem(1, 2);

        $item = $this->addItem(1, 5, false);

        $this->assertEquals('7.14', $this->laracart->total(false));

        $this->assertEquals('7.00', $this->laracart->subtotal(false));


That is the test I just wrote, (top is taxable, bottom one is non taxable) and both tests past. Can you letm e know how im able to reproduce ?

**Comment by sunscreem** [comment]
Oh - I'm adding items using the `addLine` method:

```
 $item = LaraCart::addLine(
            $productVariation->id,
            $productVariation->name,
            $quantity,
            $productVariation->price->net->inPounds(),
            [],
            ($productVariation->vat ? true : false)
        );
```
Would this make a difference? I can't remember exactly why I added the items this way. I think it was so I get the product hash on the $Item.

**Comment by lukepolo** [comment]
Shouldn't make a difference , all that does it makes sure each item is unique and does not up the QTY if the exact same items comes through

**Comment by sunscreem** [comment]
Thank Luke - I'll go and dig in to my code again and try to recreate the problem - I'll back to you soon

**Comment by lukepolo** [comment]
Sorry about all of this , feel free to add me on skype luke.a.policinski if you need more real time help~

**Comment by sunscreem** [comment]
Luke - Please don't apologise - you're giving your time for free here. Its me who should be apologising. I'm closing this issue and going to ask it again now I've got my head round what I need to happen.
