### ISSUE TITLE
Can the Laracart::subTotal() function have the option of calculating the sub-total with tax?

### ISSUE THREAD

**Issue by sunscreem** [lukepolo/laracart#156]
I'd like to be able to show the subtotal of all the items in my customers cart before fees but WITH tax.

The subtotal function doesn't give me the option to specify to include tax or not (the doc block gives me the impression that it should)? 

```
     /** Gets the subtotal of the cart with or without tax.
     *
     * @param bool $format
     * @param bool $withDiscount
     *
     * @return string
     */
    public function subTotal($format = true, $withDiscount = true)
    {
        $total = 0;

        if ($this->count() != 0) {
            foreach ($this->getItems() as $item) {
                $total += $item->subTotal(false, $withDiscount);
            }
        }

        return $this->formatMoney($total, null, null, $format);
    }
```

**Comment by lukepolo** [comment]
Wouldn't that just be the total >?

**Comment by sunscreem** [comment]
The total includes the fees (in my case shipping charge)?

Here's a screen grab so you can see where I'm hoping to get to:

![screenshot-kilt2016 app 2016-10-16 15-13-12](https://cloud.githubusercontent.com/assets/7523595/19418016/3f3140ca-93b3-11e6-9c3d-c7d6f68ee4f9.png)

**Comment by lukepolo** [comment]
Gotcha we probably should add another parameter on the totals function to not add fees since we already do with discounts and taxes on the totals function . Thoughts ?

**Comment by lukepolo** [comment]
1.1.32 now allows for it~

**Comment by sunscreem** [comment]
That would work ;) I'll merge into my fork and give it a go.

**Comment by sunscreem** [comment]
Luke - a million thank you's!

I owe you a coffee/beer/wine!

![screenshot-kilt2016 app 2016-10-16 15-45-09](https://cloud.githubusercontent.com/assets/7523595/19418225/9bd78efc-93b7-11e6-9e2e-3f4084b2fd3a.png)

**Comment by lukepolo** [comment]
No problem ! Glad it worked!
