### ISSUE TITLE
Session issues

### ISSUE THREAD

**Issue by it-can** [lukepolo/laracart#160]
Hi,

I have a checkout screen where I show my cart and calculate fees like this:

```
/**
     * Show checkout
     *
     * @param Request $request
     * @return \Illuminate\View\View
     */
    public function getCheckout(Request $request)
    {
        $cart = LaraCart::setInstance('cart1');

        // remove fee and add again
        LaraCart::removeFee('shipping');

        if ($request->input('test') == 'USA')
        {
                LaraCart::addFee('shipping', 25, false, [
                    'code'    => 'USA',
                    'country' => 'United States of America',
                ]);
        }

        $items = LaraCart::getItems();

        return view('cart.checkout', compact('cart', 'items'));
    }
```

When the checkout form is posted, the ```old_input``` in my session in gone... When I comment the ```removeFee``` and ```addFee``` stuff, it works again...

**Comment by lukepolo** [comment]
Looking to see what removing / adding fees is doing to the session

**Comment by lukepolo** [comment]
I believe what is happening is , when the session is modified any way `old_input` disappears , so 2 ways to fix this. 1 store your old input somewhere else , 2 we can try to fix it in LaraCart to reset the `old_input` after we modify the session instead of erasing it

**Comment by it-can** [comment]
Aaah ok, took me 3 hours to finally to put my finger on it... I think old_input needs to be alive and kicking by default...?

**Comment by lukepolo** [comment]
I agree, id say lets try to fix it in LaraCart

**Comment by it-can** [comment]
I created a workaround for my code now, so my problem is fixed...

**Comment by lukepolo** [comment]
K, will look into regardless thanks for letting me know~ Also may help others to know what you did .

**Comment by it-can** [comment]
When the checkout is loaded I do a ajax request to update shipping fees...

**Comment by lukepolo** [comment]
Thanks, thats how I do it on my current production site as well~

**Comment by it-can** [comment]
I see there is a ```reflash()``` function in Laravel, maybe you can do something with that?

https://laravel.com/docs/5.3/session#flash-data

**Comment by lukepolo** [comment]
#161 You want to give that a try ?  (you can modify the vendor files directly , just remember to revert it back)

**Comment by lukepolo** [comment]
Thanks ! Closing~

**Comment by lukepolo** [comment]
You can now use https://github.com/lukepolo/laracart/releases/tag/1.1.35

**Comment by it-can** [comment]
Cool! Thanks!
