### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by nepropadejtepanice** [lukepolo/laracart#163]
Hi, 

I'm trying to store cart to the database, but i get this error:
`Serialization of 'Closure' is not allowed`

I think its because _#AuthManager->#userResolver_ which is Closure.

>LaraCart {#342 ▼
  #events: Dispatcher {#5 ▶}
  #session: SessionManager {#328 ▶}
  #authManager: AuthManager {#345 ▼
    #app: Application {#3}
    #customCreators: []
    #guards: []
    #userResolver: Closure {#346 ▶}
    #customProviderCreators: []
  }
  +cart: Cart {#329 ▶}
  +prefix: "laracart"
  +itemModel: "App\Models\Test"
  +itemModelRelations: []
}

Laravel v5.3.26 & Laracart 1.1.35

Thank you for your help

**Comment by lukepolo** [comment]
Most likely that is the issue, ill have to take a deeper look after work today. - 6 hours from now~

**Comment by lukepolo** [comment]
I looked into it but will require more research to make sure thing would work doing this method.

**Comment by joaojoyce** [comment]
Any news on this issue? Any known workaround? 

Thank you.

**Comment by lukepolo** [comment]
Well we could include : https://github.com/jeremeamia/super_closure

**Comment by lukepolo** [comment]
!!!! Laravel has it already! Let me see if we can just add it , 1 sec

**Comment by lukepolo** [comment]
Ok cool so since its already included all you need todo is 


```
$serializer = new Serializer();
$cartSerialized = $serializer->serialize(\LaraCart::getInstance());
```


Then later on do 
`$serializer->unserialize($cartSerialized)`
