### ISSUE TITLE
Quantity always equal 1 when i used model binding

### ISSUE THREAD

**Issue by csmind** [lukepolo/laracart#164]
I tried something simple like this
`    $product = \App\Products::find(10);`
    `$item = LaraCart::add($product->id, $product->product_title, '10');`
    `return $cart = LaraCart::getItems();`

the quantity here equal 10 but always equal 1 ,While i'm using model binding 

i found this lines:  at [LaraCart.php](https://github.com/lukepolo/laracart/blob/master/src/LaraCart.php#L228) line : 228 

`if (empty($qty = $name) || !is_int($name)) {`
            `   $qty = 1;`
` }`

When i remove this lines it's working fine 

How can add custom quantity in this situation without removing this lines ?

Thanks.

**Comment by nepropadejtepanice** [comment]
Hi csmind,   

you can add quantity after adding item to cart. 
Like this:
```
$item = LaraCart::add($product_id);
$item->qty = $quantity;
```

**Comment by csmind** [comment]
@nepropadejtepanice  
Thanks for your reply , but this will replace the quantity value if quantity equals 5 before
this code: 
`$item = LaraCart::add($product_id);`
`$item->qty = 10;`
then the quantity will be equal 10, what i'm trying to do here to make it equals 15 add more 10

**Comment by lukepolo** [comment]
@csmind ill go write a test for this now

**Comment by lukepolo** [comment]
@csmind 

I fixed this in `1.1.36` the intent was if you just want to do something like

`$item = LaraCart::add($product->id, '10');`

You could , I changed it so you could do this as well~

**Comment by lukepolo** [comment]
https://github.com/lukepolo/laracart/commit/fb4605f11384a55e215341c6a8552c960f953d00

**Comment by csmind** [comment]
Thanks, You done a great work in this package :)

**Comment by lukepolo** [comment]
No problem! 2.0 is much cleaner , but haven't had the time to make sure its working properly for regression etc.

**Comment by csmind** [comment]
Keep it up , We are waiting for v2.0 :)
