### ISSUE TITLE
Set tax on cart items

### ISSUE THREAD

**Issue by matejsvajger** [lukepolo/laracart#170]
CartItem takes tax by default from config file. Only way to change it is with a subsequent update.

If shop has items that fall into more than one tax category it would be good to be able to set the tax while adding the item into cart.

**Comment by lukepolo** [comment]
You can do it in one swoop

`
LaraCart::add(2, 'Shirt', 200, 15.99, [
    'size' => 'XL',
    CartItem::ITEM_TAX  =>  .12
]);

`

**Comment by matejsvajger** [comment]
Nice! Didn't notice it acts as an option! Thanks!

**Comment by jmarcher** [comment]
@lukepolo I noticed there is no way to add fixed price taxes, only percentages is there a workaround for this?

**Comment by lukepolo** [comment]
If you need a fixed price for taxes, id add it as a fee possibly . Does #190 fix this issue for you>?
