### ISSUE TITLE
Question about Coupons!!!

### ISSUE THREAD

**Issue by davodavodavo3** [lukepolo/laracart#175]
Why when a discount sum of coupon exceeds the total amount in the card whe have zero discount?
Example: if total of cart is 400$ and discount of fixed coupon is 600$ , then we have 0 of totalDiscount.

I think that is not a totaDiscount should be zero, and the cart LaraCart::total.

**Comment by lukepolo** [comment]
hhmm looks like a bug cause


https://github.com/lukepolo/laracart/blob/master/src/Coupons/Fixed.php#L44

**Comment by lukepolo** [comment]
writing the test now will get back to you

**Comment by lukepolo** [comment]
#177 
this should fix your issue

**Comment by davodavodavo3** [comment]
Thanks lukepolo! I have create my CUSTOM COUPONS class from you example. And there is another functionality that will be great if you add.
$this->checkMinAmount($this->minAmount, $throwErrors);

Add $format in checkMinAmount to catch exception on windows mashines))))))
Thanks, I will not detain you))))

**Comment by davodavodavo3** [comment]
And will be innovations in the package Luke?

**Comment by lukepolo** [comment]
I have a version 2 in the works but unable to commit till I finish another project

**Comment by davodavodavo3** [comment]
Great mean very useful package you are created.Best of the best

**Comment by davodavodavo3** [comment]
Get over here!!!!)))))))))

**Comment by davodavodavo3** [comment]
Hmmm Luke ,doesn work((((

**Comment by davodavodavo3** [comment]
I paste your changes and now there is another issue.
I have product with price =  $800;.
I have fee shepping = $350;
I have coupon = $1000;

Cart total without coupon show me $1150 = noraml;
When i added a coupon cart total show me $350 ($1150 - 1000)

**Comment by lukepolo** [comment]
Will fix tmw , fever of 102, not a good idea to code . If you do fix it I'll acceotOR

**Comment by lukepolo** [comment]
PR*

**Comment by davodavodavo3** [comment]
I should fix it or my project will die))))))
When i get the solution i will write you

**Comment by davodavodavo3** [comment]
`public function discount($throwErrors = false)
    {

        //Get total of cart with fees
        $cartTotal = LaraCart::subTotal(false);
        $cartTotal += (float) LaraCart::feeTotals(false);

        if($cartTotal < $this->value){

            $this->value = $cartTotal;

        }

        return $this->value;

    }`

**Comment by davodavodavo3** [comment]
This is for fixed coupon.Only i dont know if the tax will fork.

**Comment by davodavodavo3** [comment]
Luke is there a functionality to add default fee on session cart create?

**Comment by lukepolo** [comment]
#178 thanks for @aditya-cherukuri you can do this now, also fixed the issue of the default value you stated above , please let me know if anything else is wrong

**Comment by davodavodavo3** [comment]
ok
