### ISSUE TITLE
When item qty is zero shouldn't it be removed from cart automatically?

### ISSUE THREAD

**Issue by vsiguero** [lukepolo/laracart#181]
Hi, first to say this is a nice library for Laravel 5.x.
When I build my app controllers using LaraCart, I've comme accross an issue with items having zero qty values, but they don't remove themselves from Cart. Is this the expected behavior? If so, how can I manage to remove them once their qty is equal (or less) zero?

**Comment by lukepolo** [comment]
That should not happen, if qty == 0 it should remove, let me look to see where that is

**Comment by lukepolo** [comment]
https://github.com/lukepolo/laracart/blob/master/src/LaraCart.php#L300 , are you using decrement?

**Comment by lukepolo** [comment]
We also check here : https://github.com/lukepolo/laracart/blob/master/src/Traits/CartOptionsMagicMethodsTrait.php#L46 

So im not sure how you were able to do this. Can you post how you you did this

**Comment by vsiguero** [comment]
No I wasn't! I did not look right at the code, I was just using the documentation to code. Thank you much!

**Comment by lukepolo** [comment]
Are you able to reproduce this bug ?

**Comment by vsiguero** [comment]
Hi @lukepolo I was using updateItem() method and setting the qty attribute to 0, that way the item remains in the cart, but with no qty and cart total amount to zero.

**Comment by lukepolo** [comment]
KK, will write a test to do the same make sure it gets rid of the items. Thank you!

**Comment by lukepolo** [comment]
Fixed in 1.2.4
