### ISSUE TITLE
Get specific item and remove it from the cart

### ISSUE THREAD

**Issue by GojkoC** [lukepolo/laracart#184]
I am trying to get a specific item and remove it, but with no success. I'm sending an item id through the form. Tried with find method, not working. Tried to supply the hash, but then an ErrorException is thrown-invalid argument supplied for foreach in Laracart. Does anyone have an idea how to solve this? By the way, great package. Thanks.

**Comment by lukepolo** [comment]
There is 2 ways todo this : 

1. $matches =` LaraCart::find(['id' => 123]);`
2. Each item has a hash with it , `$itemHash = $item->getHash()`

let me know if you have any other issues, (and close this one if i solved it)

**Comment by GojkoC** [comment]
Hey, thanks for the quick response. It didn't work for me that way. This is how I managed to get it work.
`public function destroy(Request $request)
    {
       $items = $this->cart->get()->getItems();

        foreach ($items as $item) {
            if ($item->id == $request->id) {
                $this->cart->removeItem($item->itemHash);
            }
        }
        return back();
    }`
Thanks again.

**Comment by lukepolo** [comment]
Will make it work like that

**Comment by lukepolo** [comment]
ah it would have returned an array , fixing to just return single match if count == 1

**Comment by lukepolo** [comment]
this is a breaking change in some code, releasing as 1.3
