### ISSUE TITLE
losing session data on redirects

### ISSUE THREAD

**Issue by jbowm2** [lukepolo/laracart#189]
I am sure I am just missing a set-up step, but I continue to lose my session data when redirecting. Happening specifically on a couple of routes. I noticed I am not persisting my cart_session_id into the database and assume this is the issue. 

adding items to cart is working, I can dump the items and see them there. 
My cart.review route has the items and displays the total from this point everything is correct. 
Any redirection from this point I am losing all of my cart data. 

random note: Still working with PatronPath?

**Comment by lukepolo** [comment]
If you have a redirect it will not save session data unless told specifically todo so (common thing in laravel)

So I would just do `LaraCart::update()` manually  

Let me know if that doesn't work!

-----
I left PatronPath about a year and half ago ~ Kinda miss it sometimes!

**Comment by jbowm2** [comment]
I had this in the code, 
`$cart_name = LaraCart::getAttribute('label');
        if($cart_name == null)
        {
            Laracart::setInstance('Cart');
            $cart_name = LaraCart::setAttribute('label', Auth::user()->name .  "'s Cart");
        }
$cart = LaraCart::get('Cart');
 $cart->update();`

at this point the cart_session_id is still not set in the users table, does this need to be set manually? in the source code I thought Laracart::get() was setting it there

**Comment by lukepolo** [comment]
When using `get` it should grab the users session id from the database

https://github.com/lukepolo/laracart/blob/master/src/LaraCart.php#L90

To set the users cart session id `update` should handle it
https://github.com/lukepolo/laracart/blob/master/src/LaraCart.php#L147

Did you make sure your config has `cross_devices` turned on? 


Or mabye for some reason the check saying auth isnt working properly ?

**Comment by jbowm2** [comment]
cross_devices is now set to true -- still losing the cart. 

`if($request->print_listing){
            $promotion = Product::where('name', 'print_listing')->first();
            $listing->print = 1; // todo change this feature in the database for the listing
            $item = LaraCart::addLine(
                $promotion->id, $promotion->name, 1, $promotion->price, [], 0, 0
            );
        }

        $cart_name = LaraCart::getAttribute('label');
        if($cart_name == null)
        {
            $cart_name = LaraCart::setAttribute('label', Auth::user()->name .  "'s Cart");
        }

        $cart = LaraCart::get();
        $cart->update();

        $listing->save();

        return redirect()->route('realtor.detail', ['slug' => $slug]);
`
added item to the cart -- from here everything looks good, I can see items in the cart everything's correct. I can move around within the site and continue to add items to the cart from here. 

I have a href that leads to the review of the cart -- once here the cart still looks correct.

`$user = Auth::user();
        $items = LaraCart::getItems();
        $total = LaraCart::total($formatted = false, $withDiscount = true);

        $cart = LaraCart::get();
        $cart->update();

        return view('cart.review', compact('items', 'user', 'total', 'cart_name', 'cart'));

`
at this point the review screen is correct, all items accounted for.  If I leave this view, I lose the cart.

**Comment by lukepolo** [comment]
Do you have a public repository that I could test with ? If not I can create one this week to get it working , im not sure why its broken currently

**Comment by jbowm2** [comment]
its a private repo.

**Comment by lukepolo** [comment]
I just tested this and it works, what cache system are you using?

**Comment by lukepolo** [comment]
you can test with this repo

https://github.com/lukepolo/laracart.lukepolo.com

/register , then go to /cart 

This should work on live, but had a bug with https://codepier.io, fixing that as we speak~

**Comment by jbowm2** [comment]
pulled your repo down and got everything set up, pretty non-descript error when i hit '/'

Sorry, the page you are looking for could not be found.

**Comment by lukepolo** [comment]
make sure to setup the .env file and turn debugging on, also i fixed the issue on my server 

You can do 
https://laracart.lukepolo.com/register
then login
https://laracart.lukepolo.com/login
then go to
https://laracart.lukepolo.com/cart

**Comment by jbowm2** [comment]
got your repo up and running on my dev environment  i'll take a look around and see if i can spot whats wrong with my project. Thanks

**Comment by jbowm2** [comment]
Ok, so I changed addLine() to add(), and now the cart_session_id is being persisted to the database.

 added item to cart: dumped cart in review screen
`Cart {#236 ▼
  +tax: null
  +fees: []
  +items: array:1 [▼
    0 => CartItem {#237 ▼
      #itemHash: "RvFmBEANk6SlSBghtnM02vDLVQygYxu72jFstZ3p"
      #itemModel: null
      #itemModelRelations: []
      +locale: null
      +lineItem: 0
      +discount: 0
      +subItems: []
      +couponInfo: []
      +internationalFormat: null
      +options: array:6 [▶]
    }
  ]
  +locale: "en_US.UTF-8"
  +instance: "default"
  +coupons: []
  +attributes: array:1 [▼
    "label" => "Stephanie Pratt's Cart"
  ]
  +multipleCoupons: false
  +internationalFormat: false
}`

cart looks good at this point. 
If the user navigates away from this view, I will lose this cart info. Any other view the cart stays intact?

**Comment by lukepolo** [comment]
Not in the repo , you can make one though.

I can look into why `addLine` doesn't save the cart_session)id

**Comment by jbowm2** [comment]
ok in your repo I added this: 

in the web. php in the auth grouping i added a route
`Route::get('/cart/review', 'CartController@review');`

in the cart controller i added this method
`public function review()
    {
        return view('review');
    }
`
and made a view called review.blade.php
`
{{ dump(LaraCart::get()->cart) }}

Total
{{ LaraCart::total() }}
<br><br>
<table id="cart-itemd" class="table-bordered" style="width: 95%">
    <thead>
    <tr class="header-row">
        <th>Item Name</th>
        <th>Price</th>
    </tr>
    </thead>
    <tbody>
    @foreach($cart = LaraCart::getItems() as $item)
        <tr>
            <td>
                <button title="remove item" class="btn-danger" onClick="window.location.reload()">
                    <i class="fa fa-times-circle" aria-hidden="true">{!! LaraCart::removeItem($item->getHash()) !!}</i>
                </button>
                {!! $item->name !!}
            </td>
            <td>{!! $item->price($formatted = true)  !!}</td>
        </tr>
    @endforeach
    <td></td>
    <td>Total: ${{ LaraCart::total() }}</td>
    </tbody>
</table>

<a href="/cart">Continue</a>
`

 I added several items to the cart then hit /cart/review in the URL and the cart was intact, then clicked the continue link which leads back to the /cart and the cart is empty.

**Comment by lukepolo** [comment]
Sounds good, now that its reproducible ill go and try to fix it

**Comment by jbowm2** [comment]
it was this line:

<i class="fa fa-times-circle" aria-hidden="true">{!! LaraCart::removeItem($item->getHash()) !!}</i>

every time the page loaded i was calling this method within the loop. and clearing out the cart. 
LaraCart was working as expected. 

thanks for the help

**Comment by lukepolo** [comment]
AH perfect ! Glad its working
