### ISSUE TITLE
Cart is empty when I try to share cart items with all views

### ISSUE THREAD

**Issue by dallen66** [lukepolo/laracart#199]
I add these line to the AppServiceProvider
```php
public function boot()
    {
        $cartitems =LaraCart::getItems();
        //dd($cartitems);  //empty array []
        view()->share('cart_items', $cartitems);
    }
```

I all so add the to the BaseController
```php
    protected $cartitems;

    public function __construct()
    {
        // Fetch the Site Settings object
        $this->cartitems = LaraCart::getItems();
        //dd($this->cartitems); //empty array []
        View::share('cart_items', $this->cartitems);
    }
```
If the above codes are active and I add the line below any where in my app, it also come back empty.
```php
  $cartitems =LaraCart::getItems()
```

**Comment by lukepolo** [comment]
I believe the session has not been booted yet in the constructor , also dd stops sessions from saving so that's a bad test , I would dump it in your views instead with a dump . Im currently on vacation but will be able to show you an example of middleware that can handle this when I get back (next Tuesday)

**Comment by dallen66** [comment]
Thank for replying.

I tested it without dd same issue.
No rush, I found a work around, using ajax java-script (not an ideal solution)

Thanks

**Comment by lukepolo** [comment]
This works for me 


```php
<?php

namespace App\Http\Middleware;

use Closure;
use LukePOLO\LaraCart\Facades\LaraCart;

class LoadCart
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $cartItems = LaraCart::getItems();
        view()->share('cartItems', $cartItems);
        return $next($request);
    }
}
```

Then add it to your web middleware

```php
 protected $middlewareGroups = [
        'web' => [
                ... other middleware
                \App\Http\Middleware\LoadCart::class,
        ]
  ]
```

**Comment by lukepolo** [comment]
https://github.com/lukepolo/laracart.lukepolo.com/blob/master/app/Http/Middleware/LoadCart.php

https://github.com/lukepolo/laracart.lukepolo.com/blob/master/app/Http/Kernel.php
