### ISSUE TITLE
Laracart getItems returns empty array even though session has content

### ISSUE THREAD

**Issue by mjanssen** [lukepolo/laracart#204]
`LaraCart::getItems()` returns an empty array, even though items are added.
Printing the session from the $request variable returns a 'laracart' key though (see screenshot).

![image](https://user-images.githubusercontent.com/1145427/31097640-409a9908-a7c0-11e7-86b5-491041217eb3.png)

What's going on here?

**Comment by mjanssen** [comment]
`Laracart::get()` returns:

![image](https://user-images.githubusercontent.com/1145427/31097963-62d0480a-a7c1-11e7-9adc-73916a566a4c.png)

**Comment by lukepolo** [comment]
If your using DD to test this , it will not persist in the session. Make make sure to allow it to save to the session then do a DD.

**Comment by mjanssen** [comment]
If I'm allowing Laravel to render the view, and just putting a `print_r` on top, the array is still empty 🤔

**Comment by lukepolo** [comment]
How are you adding things to your cart? And where are you testing this `print_r` ?

**Comment by mjanssen** [comment]
The items are added in a controller, on the `/` route. For testing purposes I'm using
```
// From the docs
LaraCart::add(3, 'Shirt', 200, 15.99, [
    'size' => 'XL'
]);
```
I'm trying to get the items from a different controller, and a different route (`/cart`) using the `LaraCart::getItems()` function.

**Comment by lukepolo** [comment]
I guess theres 2 things you need to make sure of 

1. Your session is actually working (test logging in)
2. You should have to hit the home page once 
3. Make sure the session has been started before you hit a DD

I would do a dump on the `/` home route in a view to make sure your session is working, this way you know its working.

**Comment by mjanssen** [comment]
All right, build some small authentication script, but it seems sessions are not functional. This might be a Laravel issue on my side 🤔 ...

**Comment by mjanssen** [comment]
Hmm, Auth::check() does return `true` when Auth::attempt is executed, even on other pages. So that shouldn't be the problem

**Comment by mjanssen** [comment]
And I am able to retrieved items using `LaraCart::get()->cart->items`

**Comment by lukepolo** [comment]
what version of laracart, ill make a test later tonight to confirm.

**Comment by mjanssen** [comment]
Laracart version: 1.3.7
laravel version: v5.4.36

**Comment by mjanssen** [comment]
Sidenote: I tried both `php artisan serve` and homestead vagrant, both have the same result.

**Comment by mjanssen** [comment]
Getting the session file from `storage/framework/sessions` also results in a valid Laracart session (screenshot).

![image](https://user-images.githubusercontent.com/1145427/31100247-fb07d942-a7c8-11e7-81e3-f926a8369905.png)

**Comment by lukepolo** [comment]
![image](https://user-images.githubusercontent.com/2066668/31101375-646ed422-a79b-11e7-997b-ffb58a56bd81.png)

Seems to work for me ,

**Comment by lukepolo** [comment]
Is this an open source project I can take look at? My tests are also passing

**Comment by lukepolo** [comment]
Clean install also works

https://github.com/lukepolo/laracart-test

Look through that repo and you see how i did it

**Comment by mjanssen** [comment]
All right, let me look into it. The project is not open source though.

**Comment by lukepolo** [comment]
Yah not sure whats going on, works in that repo on a clean instance, let me know what you find out,

**Comment by mjanssen** [comment]
I guess there's still something wrong with the setup.

```
LaraCart::add(3, 'Shirt', 200, 15.99, [
    'size' => 'XL'
]);
```

Is called in the HomeController, which results in the following in the view

![image](https://user-images.githubusercontent.com/1145427/31138923-4ddef66c-a870-11e7-8c72-1a50773c8368.png)

But when the `LaraCart::addItem()` is removed from the controller, it results in an empty array in the view.

![image](https://user-images.githubusercontent.com/1145427/31139161-f02e0854-a870-11e7-9eeb-52dafc72cc19.png)

**Comment by lukepolo** [comment]
is this on your app or the repo i setup?

**Comment by lukepolo** [comment]
@mjanssen Any update?

**Comment by mjanssen** [comment]
@lukepolo Dove into it again yesterday. Updated Laravel to the 5.5 version, changed session driver to redis, installed redis requirements and everything magically started working. I think something weird was going on with my sessions...

**Comment by lukepolo** [comment]
Cool , glad its working
