### ISSUE TITLE
Get Model field when displaying the cart

### ISSUE THREAD

**Issue by t-prod** [lukepolo/laracart#205]
Hi,

I would like to get the real quantity field of my model. Get the model attributes.
In config/laracart.php I've already linked to the Model
Here is my code :

```
@foreach(LaraCart::getItems() as $item)
{{ $item->options['qty'] }} <= quantity in cart
{{ $item->model->quantity }} <= quantity field in my product ??? How can I do ?
@endforeach
```
It's to avoid a user a quantity superior to my original product's quantity.

Thanks for your help and congratulations for your package !

Regards

**Comment by lukepolo** [comment]
Just do $item->qty = $item->model->quantity 

But if you insist of having it read from your qty on your model all the time just change it in the config 

https://github.com/lukepolo/laracart/blob/master/src/config/laracart.php#L113

**Comment by lukepolo** [comment]
@t-prod Let me know if it doesn't work for you

**Comment by t-prod** [comment]
Thanks for your answer.
I think I'm not clear.
Is it possible to get model attribute via $item (loop LaraCart::getItems()) ?
It avoids me a query for each $item in the loop.

Do you see what I mean ?

**Comment by lukepolo** [comment]
Oh, I understand now. Let me make a couple of changes to allow for that type of thing.

**Comment by t-prod** [comment]
Wonferful ;) Thanks again to be so reactive ;)

**Comment by lukepolo** [comment]
Working on this now! SOrry for the wait, been really busy !

**Comment by lukepolo** [comment]
Ok so now you can do `$item->model` !

https://github.com/lukepolo/laracart/pull/213
release 1.4.2
