### ISSUE TITLE
subTotal() is calculated incorrectly in conjunction with discounts

### ISSUE THREAD

**Issue by dennisoderwald** [lukepolo/laracart#206]
Hi,

as it seems, `subTotal()` is calculated incorrectly in conjunction with discounts.

An example:
```
$item = LaraCart::add($product->id, $product->title, 1, 200, [], true, false);

$coupon = new \LukePOLO\LaraCart\Coupons\Percentage('100OFF', 1.0, [
  'description' => 'Coupon'
]);

LaraCart::addCoupon($coupon);

dd(LaraCart::subTotal());
```

`subTotal()` returns `200` instead of `0`

If I refer the discount to an item, `subTotal()` calculates correctly, but it is not considered in `totalDiscount()`.

```
$coupon->setDiscountOnItem($item, $coupon->discount());
```

Or do I misunderstand the use of the function?

**Comment by lukepolo** [comment]
I will look at this tonight, but i believe subTotal should not show discounts

**Comment by lukepolo** [comment]
Ok, so I thought it was a bug but its intended to work this way. As the discount doesn't belong on the item but on the total of the cart in your first case, cause its 100% off the carts total not an item. hence why your seeing this issue. 

Only thing not intended is the totalDiscount , but there are some issues of fixing that as it will break the totals in general.

**Comment by lukepolo** [comment]
#207 

Fixed the issue with total discount
