### ISSUE TITLE
Set taxable on Cart on case-by-case basis

### ISSUE THREAD

**Issue by spaceageliving** [lukepolo/laracart#214]
I'd like to be able to enable tax calculation at the cart level, for example, if a "ship to" state value is a certain state.  Is it possible to do this?

**Comment by lukepolo** [comment]
Sure, you can use laravels config helper to set the taxation to on and off . When they change the state just flip the taxation on or off.

Does this work for you?

**Comment by spaceageliving** [comment]
Perfect, thanks Luke.

**Comment by lukepolo** [comment]
no problem, let me know if that doesn't work. Its actually how I test it in our tests ( so it should!)
