### ISSUE TITLE
trouble documentation!

### ISSUE THREAD

**Issue by robertnicjoo** [lukepolo/laracart#215]
Hi,
With respect but your documentation is no help at all!

Ok, now I installed brand new laravel and after auth I installed your project then what?!

example:  https://laracart.lukepolo.com/master/basic-usage#adding add those in where? model? which model?, controller? which one? etc.

is there any good documents about your project or videos that you know and I can't find? if there is please provide links.

Thank you.

**Comment by lukepolo** [comment]
This is up to you, but I would suggest in the controller. This package doesn't dictate how you build your application.
