### ISSUE TITLE
Charge VAT if in VAT Zone

### ISSUE THREAD

**Issue by RolloskiDev** [lukepolo/laracart#216]
I was just wondering if it would be possible to only charge VAT if the customer is in a VAT zone? e.g if they live in England they get charged VAT. but if they live in america, they do not?

I would imagine I would have to write some sort of helper for this?

**Comment by lukepolo** [comment]
Yah we have something simlar but more based on which state they live in. But your on the right track as I would check on, checkout / adding items,  if they live in that area set the tax rate via the laravel config helper.
