### ISSUE TITLE
Using instances for shopping cart

### ISSUE THREAD

**Issue by nehulagr** [lukepolo/laracart#221]
Hello, I am new to this package. And as per package its a great package it solves my purpose easily. But there is one thing that I want to add product to to different instances like one where person wants to buy a product and another where the user is purchasing a product. 

So I want two instances

1) shopping-cart
2) wishlist

Now I am not sure as per your documentation how can I use it. If you can provide any brief idea or example it will be really helpful. 

Thank you! :) and thanks for such an amazing package.

**Comment by lukepolo** [comment]
@nehulagr Thanks for the kind words! Ill be home later today and ill code up a simple example to show how you todo this.

**Comment by lukepolo** [comment]
@nehulagr Im so sorry, i forgot to come back to this question! I promise Ill have an example out tonight !!!

**Comment by lukepolo** [comment]
Ok so what you can do is set / and get the instance you need to work with

For instance

`
$cart = LaraCart::get('wish-list');
$cart->add(
            str_random(10),
            $name = $faker->name,
            $qty = $faker->numberBetween(0, 10),
            $price = $faker->numberBetween(0, 10),
            $options = [
                'color' => $faker->colorName
            ],
            $taxable = $faker->boolean(),
            $lineItem = false
        );
`

in your view make sure you return the correct cart! 

```
@php
    $cart = \LukePOLO\LaraCart\Facades\LaraCart::setInstance('wish-list');
    dump($cart->cart->instance);
@endphp

```

After setting the cart you can use $cart just like `LaraCart`


let me know if this help!s
