### ISSUE TITLE
Apply coupon to fees

### ISSUE THREAD

**Issue by Krbec77** [lukepolo/laracart#224]
Hello, 
At first let me say that this package is very good and I like it. I just want to ask if it is possible to apply coupon also to fees. For example when I have some items in cart and also delivery fee I would like to apply percentage coupon on whole price including the fee. Could you tell me if it is possible please? If so, how can I do it? 
Thank you very much in advance

**Comment by lukepolo** [comment]
It can! You will have to create your own coupon though , which is pretty simple. Just copy the existing discount coupon into your app. After that modify the code (probably use `total` function) . Once you completed your coupon just reference the new one like you did with the existing one.
