### ISSUE TITLE
taxTotal() is calculated incorrectly in conjunction with discounts

### ISSUE THREAD

**Issue by dennisoderwald** [lukepolo/laracart#226]
Hi,

as it seems, `taxTotal()` is calculated incorrectly in conjunction with discounts.

An example:

```
// Add item
$item = LaraCart::add(1, 'Product with 19% Tax', 1, 100.00, [CartItem::ITEM_TAX => .19]);

// Apply a 50 EUR Coupon
$coupon = new \LukePOLO\LaraCart\Coupons\Fixed('50EUR', 50, [
    'description' => '50EUR'
]);
LaraCart::addCoupon($coupon);

dd(LaraCart::taxTotal());
```

`taxTotal()` returns `-31.00`
`total()` returns `19.00`

However, it should correspond to the following values:

```
taxTotal: 11.02
total: 69.00
```

My configuration parameters:

```
tax_by_item => true,
discountTaxable => true
```

I use Version `1.3.8`

Thanks for your contribution & hard work @lukepolo!

**Comment by dennisoderwald** [comment]
When I use dev-master, I get the following results:

```
taxTotal: 19.00
total: 69.00
```

This is really confusing and also wrong.

**Comment by lukepolo** [comment]
will write a test for it, and see whats going on.

**Comment by dennisoderwald** [comment]
@lukepolo Thanks for your fast response. Can you give me an ETA? Then I base my planning on that. It's critical, I'm afraid.

**Comment by lukepolo** [comment]
I can do it now, also if you want we can work together on this via skype / slack

**Comment by dennisoderwald** [comment]
@lukepolo Awesome - I'll send you an e-mail. :-)

**Comment by lukepolo** [comment]
This feature has been added , along with a new function for netTotal and gross Discounts
