### ISSUE TITLE
No currency symbol € for Euro with locale 'de_DE.UTF-8'

### ISSUE THREAD

**Issue by pixelpeter** [lukepolo/laracart#231]
### Issue
This code will give me: **EUR25,00**
```
$this->laracart->formatMoney('25.00', 'de_DE.UTF-8', true)
```

and this will return: **Eu25,00**
```
$this->laracart->formatMoney('25.00', 'de_DE.UTF-8', false)
```

I expected for the 2nd version to get **€25,00**

### Question
Any reason why there's no currency symbol or is this the expected behavior?
Because `en_EN.UTF-8` will give me the `$` currency symbol.

**Comment by pixelpeter** [comment]
I just realized you're relaying on php and using `money_format()` to format the price.

That will explain the behavior.
Any plans to be more flexible with price formatting or any suggestion how I can get the above mentioned format?

Thanks

**Comment by lukepolo** [comment]
You can change that in your laracart config by publishing it with `php artisan publish` , you can change those values : 

https://github.com/lukepolo/laracart/blob/master/src/config/laracart.php#L33

**Comment by pixelpeter** [comment]
When dumping an `$item` from the cart I get this:
```
array:1 [▼
  "8b2cd0534541a80bc9178b847828b401" => CartItem {#319 ▼
    #itemHash: "8b2cd0534541a80bc9178b847828b401"
    #itemModel: null
    #itemModelRelations: []
    +locale: null
    +lineItem: false
    +discount: 0
    +active: true
    +subItems: []
    +couponInfo: []
    +internationalFormat: null
    +options: array:6 [▼
      "id" => "463"
      "qty" => 2
      "name" => "Some example product"
      "taxable" => true
      "price" => 67.226890756303
      "tax" => 0.19
    ]
  }
]
```
I'm wondering why `locale` and `internationalFormat` is `null`although it's set in the configuration

**Comment by lukepolo** [comment]
Thats cause you can actually set those per item, if your not setting them on the item its set globally. Also I think `internationalFormat` allows you to todo what you need. 

Id look up money_format to determine how to display how you want.

**Comment by lukepolo** [comment]
Looked further into this, its just how money_formatter handles it, would need to be fixed in money formatter
