### ISSUE TITLE
Call to undefined function LukePOLO\LaraCart\money_format()

### ISSUE THREAD

**Issue by ajitdas123** [lukepolo/laracart#232]
Hi lukepolo,

Thank you for this amazing package, 
I have been working with this package, and then i encountered Call to undefined function LukePOLO\LaraCart\money_format() this error . This error is like almost everywhere. What is the solution to get around this issue. 

My config file is like this : 
```
 'locale' => 'en_IN.UTF-8',

    /*
    |--------------------------------------------------------------------------
    | If true displays the international format rather thant he national format
    |--------------------------------------------------------------------------
    |
    */
    'international_format' =>  'en_US.UTF-8',

    /*
    |--------------------------------------------------------------------------
    | Sets the tax for the cart and items , you can change per item
    | via the object later if  needed
    |--------------------------------------------------------------------------
    |
    */
    'tax' => 5,
```

And my code is like this where i am getting error

```
 $coupon = new \LukePOLO\LaraCart\Coupons\Fixed('TEST01', 794, [
            'description' => 'This is test coupon'
        ]);
        $coupon->checkMinAmount(9000, $throwErrors = true);



        LaraCart::addCoupon($coupon);
        

        print_r(LaraCart::total($formatted = false) );
        echo '<br>';
        print_r(LaraCart::taxTotal($formatted = false));
```

I am using xampp server on window OS , 
Laravel : 5.5
cart package is 1.5

**Comment by lukepolo** [comment]
Sadly! Windows doesn’t support money format 😭, i probably should switch it to another package soon . Think there’s one called PHPMoney that looks good

**Comment by ajitdas123** [comment]
aww damn ok np :) its an amazing package . tyvm for this :)

**Comment by lukepolo** [comment]
I wish i had more time to work on it! Thanks for liking the package!
