### ISSUE TITLE
Is there any option to add tax while adding product to the cart ?

### ISSUE THREAD

**Issue by ajitdas123** [lukepolo/laracart#236]
Hi Lukepolo,

I was trying this package, just came across a place where i want to add tax for each product at the time of adding to cart. Is there any option to add to add tax for each product individually while adding product to the cart??
I know tax can be added from laracart config file. but i m thinking something like this 

` LaraCart::add($id, $name, $qty, $price,'',$tax);`
Something like this

I saw in the documentation that you updated the tax of a product by its hashid
`LaraCart::updateItem($itemHash, 'tax', .045);`
But can it be also done at the time of adding the product? 

At the same time i also like to ask 
In the documentation in the add item section said product can be added like this
```
// Adding an item to the cart
LaraCart::add(2, 'Shirt', 200, 15.99, [
    'size' => 'XL'
]);
```
But what is that 15.99 ? its an option or what.
If you could explain a bit i would really appreciate that. Thanks :)

**Comment by lukepolo** [comment]
```
15.99 is the price

// Adding an item to the cart
LaraCart::add(2, 'Shirt', 200, 15.99, [
    'size' => 'XL',
    'tax' => .2
]);
```

**Comment by lukepolo** [comment]
Stale
