### ISSUE TITLE
[Question] How to set discount percentage and apply it to one Item

### ISSUE THREAD

**Issue by yuliantosb** [lukepolo/laracart#238]
Hello Luke, I want to ask you, I try to add coupon percentage on my single product, but the calculation is wrong, here's my code

```
$laracart = LaraCart::add(

            1,
            $name = 'product one',
            $qty = 1,
            $price = 24,
           $options = ['tax' => .1],
            $taxable = true,
            $lineItem = false
 );

$coupon = new \LukePOLO\LaraCart\Coupons\Percentage('10OFF', .1, [
            'description' => '10%OFF'
 ]);

$add_coupon = LaraCart::addCoupon($coupon);
$coupon->setDiscountOnItem($laracart, .1);
```

The item price is $24, the discount is 10%, the discount should be $2.4 but the discount is $8.69
I don't know wheter this my fault or not.

And how if the quantity is 2, is it the discount will (24 * 2 ) 0.1 ? or Only 24 ?

Also the LaraCart::CartTotals is not deduct the discount

![screenshot from 2018-05-12 12 24 02 edit](https://user-images.githubusercontent.com/16331964/39953950-f24e1c56-55df-11e8-8f68-d099c5c5503f.png)

**Comment by lukepolo** [comment]
If it has a qty of 2 and a coupon is on that item, it will discount both. For the other issue, we will hvae to wriet some tests to figure out whats going on.

**Comment by lukepolo** [comment]
Release 1.5.13 , fixes this issue!
