### ISSUE TITLE
Amount on coupon ignored and rounded

### ISSUE THREAD

**Issue by t-prod** [lukepolo/laracart#240]
Hi,

I have a big problem here with a fixed Coupon tested with version 1.4.1 and last version 1.5.12.
Here is the example without Coupon :
![image](https://user-images.githubusercontent.com/1824638/40667880-782e4112-6363-11e8-8b70-eadd0ebb09ae.png)

Here is the example with Fixed Coupon. I want to add Tax + Fees to my Coupon  so :

![image](https://user-images.githubusercontent.com/1824638/40667992-c0494cc6-6363-11e8-9861-743d3465e929.png)

I'll pass the good amount 4.31 and then calls addCoupon with it but it displays **4.00**

`
Fixed {#537 ▼
  +code: "jackpot"
  +value: 4.31
  +appliedToCart: true
  +options: array:1 [▼
    "description" => "Cagnotte"
  ]
}
`

Code for applying Coupon is here :

```

// Add coupon jackpot
if( ($request->has('removejackpot') && $request->removejackpot == false) || session('removejackpot') == false)
{
LaraCart::removeCoupon('jackpot');
$coupon = new \LukePOLO\LaraCart\Coupons\Fixed('jackpot', floatval(session('jackpot')),
 [
                    'description' => trans('app.items.jackpot')
 ]
);
session()->put('removejackpot', false);
LaraCart::addCoupon($coupon);
$this->calculateFees();
}

```

My config file is : 

`<?php

return [

    /*
    |--------------------------------------------------------------------------
    | The caching prefix used to lookup the cart
    |--------------------------------------------------------------------------
    |
    */
    'cache_prefix' => 'laracart',

    /*
    |--------------------------------------------------------------------------
    | Locale is used to convert money into a readable format for the user,
    | please note the UTF-8 , helps to make sure its encoded correctly
    |
    | Common Locales
    |
    | English - United States (en_US): 123,456.00
    | English - UNITED KINGDOM (en_GB) 123,456.00
    | Spanish - Spain (es_ES): 123.456,000
    | Dutch - Netherlands (nl_NL): 123 456,00
    | German - Germany (de_DE): 123.456,00
    | French - France (fr_FR): 123 456,00
    | Italian - Italy (it_IT): 123.456,00
    |
    | This site is pretty useful : http://lh.2xlibre.net/locales/
    |
    |--------------------------------------------------------------------------
    |
    */
    'locale' => 'en_US.UTF-8',

    /*
    |--------------------------------------------------------------------------
    | If true displays the international format rather thant he national format
    |--------------------------------------------------------------------------
    |
    */
    'international_format' => false,

    /*
    |--------------------------------------------------------------------------
    | Sets the tax for the cart and items , you can change per item
    | via the object later if  needed
    |--------------------------------------------------------------------------
    |
    */
    'tax' => null,

    /*
    |--------------------------------------------------------------------------
    | Calculate tax per item, rather than subtotal
    | https://github.com/lukepolo/laracart/issues/180
    |
    | This will vary , please investigate to follow the rules of your local laws
    | https://money.stackexchange.com/questions/15051/sales-tax-rounded-then-totaled-or-totaled-then-rounded
    |--------------------------------------------------------------------------
    |
    */
    'tax_by_item' => false,

    /*
    |--------------------------------------------------------------------------
    | If you need to tax items before discount you can turn it on
    |--------------------------------------------------------------------------
    |
    */
    'tax_item_before_discount' => false,

    /*
    |--------------------------------------------------------------------------
    | Allows you to choose if the discounts applied are taxable
    |--------------------------------------------------------------------------
    |
    */
    'discountTaxable' => false,

    /*
    |--------------------------------------------------------------------------
    | If your discounts are already pre taxes but items are not,
    | you can set this here to to get the correct values
    |--------------------------------------------------------------------------
    |
    */
    'discountsAlreadyTaxed' => false,

    /*
    |--------------------------------------------------------------------------
    | Allows you to choose if the discounts applied to fees
    |--------------------------------------------------------------------------
    |
    */
    'discountOnFees' => false,

    /*
    |--------------------------------------------------------------------------
    | Allows you to configure if a user can apply multiple coupons
    |--------------------------------------------------------------------------
    |
    */
    'multiple_coupons' => false,

    /*
    |--------------------------------------------------------------------------
    | The default item model for your relations
    |--------------------------------------------------------------------------
    |
    */
    'item_model' => null,

    /*
    |--------------------------------------------------------------------------
    | Binds your data into the correct spots for LaraCart
    |--------------------------------------------------------------------------
    |
    */
    'item_model_bindings' => [
        \LukePOLO\LaraCart\CartItem::ITEM_ID      => 'id',
        \LukePOLO\LaraCart\CartItem::ITEM_NAME    => 'name',
        \LukePOLO\LaraCart\CartItem::ITEM_PRICE   => 'price',
        \LukePOLO\LaraCart\CartItem::ITEM_TAXABLE => 'taxable',
        \LukePOLO\LaraCart\CartItem::ITEM_OPTIONS => [
            // put columns here for additional options,
            // these will be merged with options that are passed in
            // e.x
            // tax => .07
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | The default item relations to the item_model
    |--------------------------------------------------------------------------
    |
    */
    'item_model_relations' => [],

    /*
    |--------------------------------------------------------------------------
    | This allows you to use multiple devices based on your logged in user
    |--------------------------------------------------------------------------
    |
    */
    'cross_devices' => false,

    /*
    |--------------------------------------------------------------------------
    | This allows you to use custom guard to get logged in user
    |--------------------------------------------------------------------------
    |
    */
    'guard' => null,
];
`

**Comment by lukepolo** [comment]
Try changing `'discountTaxable' => false,` to `true`, currently its set to false

**Comment by lukepolo** [comment]
Also you can make sure to not discount your fees with `discountOnFees`

**Comment by t-prod** [comment]
Hi Luke,

Thanks for your answer.
I edit this but nothing works :

```
'discountTaxable' => true,

    /*
    |--------------------------------------------------------------------------
    | If your discounts are already pre taxes but items are not,
    | you can set this here to to get the correct values
    |--------------------------------------------------------------------------
    |
    */
    'discountsAlreadyTaxed' => false,

    /*
    |--------------------------------------------------------------------------
    | Allows you to choose if the discounts applied to fees
    |--------------------------------------------------------------------------
    |
    */
    'discountOnFees' => false,
```
I think we cannot do a discount equals to the total cart. I try to look why addCoupon not do the job but I see nothing wrong. 
Do you think to anything else ? It's a important feature of one of my Laravel application ;) 

Regards

**Comment by lukepolo** [comment]
item = $4.00
Fee = $0.31
tax = (whats your tax rate)
discount = $4.00

total = item + (item * tax) + fee - discount
x = 4 - (4*.y) + .31 - 4

Confirm above~

**Comment by t-prod** [comment]
The client has got a wallet (with money credited).
Let's says the client has got 10$.

The goal is that he pays nothing if its total cart is 4.00$ + (taxes and fees included = 4.31$)
So the AddCoupon 4.31 should works to display 0.00 in total cart.

It's kind of special but it could be possible to add a coupon if it's not superior to the total cart.

**Comment by t-prod** [comment]
item = $4.00
Fee = $0.31
tax = 0.20 (20%)
discount = $4.00 (but I would like $4.31)

**Comment by t-prod** [comment]
The exact use case is :
Item = $4.00
Fee = $0.26
tax = 0.05 => 0.20 in config/laracart.php (20%)
discount wanted (addCoupon) = $4.31 (but it's not working display $4.00)
Total Cart = $0.31 (but we want $0.00)

**Comment by t-prod** [comment]
Do you find something relevant ?

**Comment by t-prod** [comment]
Ok for the total my display value was :

I change for :

**Comment by lukepolo** [comment]
I made two fixes to coupons that should fix your issue. 

ed4d082a6e21d59525251d3fd995b21428f748f3
