### ISSUE TITLE
UpdateItem event is fired seven times on add to cart

### ISSUE THREAD

**Issue by Roywcm** [lukepolo/laracart#241]
Hi,

It looks like, adding one item to the cart is firing the updateItem event seven times. 
Is this something i'm doing wrong or is it a bug?

**Comment by lukepolo** [comment]
Sounds like a bug, ill have to do change my tests to verify

**Comment by basepack** [comment]
Hi @lukepolo did you changed your tests already?

**Comment by lukepolo** [comment]
I have not , been busy with other projects. Feel free to do a PR and update the tests

**Comment by lukepolo** [comment]
#244 Will be merged once tests pass
