### ISSUE TITLE
Time out on adding a percentage coupon with tax_item_before_discount config

### ISSUE THREAD

**Issue by Roywcm** [lukepolo/laracart#245]
I cant add a percentage coupon if I set the tax_item_before_discount setting to true. 
I'm getting a timeout. 

The tests in your package confirmed this. 

Edit: It only happens when I want to set a coupon on a cart item with setDiscountOnItem().

**Comment by lukepolo** [comment]
Thanks for the report ! Feel free to take a stab at it , won’t get to it till probably this weekend

**Comment by lukepolo** [comment]
#246 Thanks for the PR!
