### ISSUE TITLE
Coupon on cart item is calculating the discount on one item. 

### ISSUE THREAD

**Issue by Roywcm** [lukepolo/laracart#247]
Hi,

If I have an item in my cart with a qty of 2, the discount will be calculated on one item instead of two.
For example:

Cartitem qty = 2
Price per Item = €20
Total price = €40
Discount = 10%

Expected discount = €4,-
Actual discount = €2,-

Is this expected behavior or a bug?

**Comment by Roywcm** [comment]
Figured out this only happens when the config tax_item_before_discount is false.

**Comment by lukepolo** [comment]
K should be easy to track down then , most likely forgot a qty multiplier

**Comment by lukepolo** [comment]
I wrote a test and seems its working 

`
        $this->app['config']->set('laracart.tax_item_before_discount', true);

        $this->addItem(2, 20);

        $percentCoupon = new LukePOLO\LaraCart\Coupons\Percentage('10%OFF', '.1');

        $this->laracart->addCoupon($percentCoupon);

        $this->assertEquals($percentCoupon, $this->laracart->findCoupon('10%OFF'));

        $this->assertEquals('10%', $percentCoupon->displayValue());
        $this->assertEquals('4.00', $percentCoupon->discount());
`

Can you write a test similar to this to make it fail how your expecting?

**Comment by Roywcm** [comment]
Yes, I fixed it in my latest pull request: #246 
Sorry, I had to close this topic. :)

**Comment by Roywcm** [comment]
Sorry, I thought I fixed in in a pull request, but that can't be right, due to date difference.. 
Checking it now.

**Comment by Roywcm** [comment]
Can't reproduce it at the moment, sorry. 
I'm closing this issue for now.
