### ISSUE TITLE
Danish currency and locale

### ISSUE THREAD

**Issue by tripex** [lukepolo/laracart#250]
Hi, I can't get it to work with the danish currency and locale, 
Any experience with this?
I have tried to change in config to use da_DK.UTF-8

**Comment by lukepolo** [comment]
@tripex Looking to see what could be the problem.

**Comment by tripex** [comment]
@lukepolo sorry, same result, not working.

**Comment by lukepolo** [comment]
Not sure if this helps but laracart uses PHP's setLocale function : http://php.net/manual/en/function.setlocale.php 

Will keep trying to figure out why it doesn't work.

What PHP Version are you running?

**Comment by tripex** [comment]
HI @lukepolo 
I'm using php 7.1 on the homestead box. 
I can't get it to work with the danish locale :(

**Comment by tripex** [comment]
Is there somewhere in basic laravel I can configure the locale correctly, just to try something different?

**Comment by lukepolo** [comment]
@tripex it uses : http://php.net/manual/en/function.setlocale.php, you can do that anywhere.

**Comment by tripex** [comment]
@lukepolo So nowhere in Laravel to to this? Not even in config/app.php?
Have you had any luck yet trying to set the locale?

**Comment by lukepolo** [comment]
You can do it anywhere in laravel . set it in the AppProvider. 

I have not, I'm not 100% sure why. You may need to add a locale or something to the server? It's a PHP thing , not a LaraCart sadly. 

I'd look at the docs for PHP and see whats happening.

**Comment by tripex** [comment]
Is this only working with dollars per default?

**Comment by lukepolo** [comment]
I cannot, i dont have the time to do this. its a PHP thing go ask on some PHP forms. It's not unique to laravel or laracart.
