### ISSUE TITLE
Laravel 5.8 support

### ISSUE THREAD

**Issue by it-can** [lukepolo/laracart#253]
Would be nice to have Laravel 5.8 support for this package! Thanks

**Comment by lukepolo** [comment]
#254 , just waiting to make sure tests all pass.

**Comment by it-can** [comment]
thanks man!

**Comment by lukepolo** [comment]
Had some complications upgrading to 5.8. But think i finally sorted it all out.

**Comment by lukepolo** [comment]
Released 1.7.0.

**Comment by it-can** [comment]
@lukepolo 1.7 is not on packagist?

**Comment by lukepolo** [comment]
Should be there now : https://packagist.org/packages/lukepolo/laracart#1.7.0
