### ISSUE TITLE
Can't use "View::Share" to display items cart count

### ISSUE THREAD

**Issue by christophe-44-27** [lukepolo/laracart#259]
Hi,
I would like to display the number of items from my cart, into my navigation bar. I want to use AppServiceProvider to facilitate my work but something weird appeared.

I don't know why, but when i use "view::share" into AppServiceProvider, my cart is empty (but my cart session is always filled).

Maybe developping an helper to count the items number could be a nice thing to have..

Regards,
Christophe

**Comment by lukepolo** [comment]
You can use `LaraCart::count()` , if you want the QTY's to be added to the count you can `LaraCart::count(true)`

**Comment by christophe-44-27** [comment]
Well same thing, it clear my cart :/

**Comment by lukepolo** [comment]
I just tested this : 


![image](https://user-images.githubusercontent.com/2066668/66330615-bd7e0280-e8fe-11e9-979a-229c3fab74e6.png)

```blade
{{ dump(LaraCart::get()->cart) }}

Total
{{ LaraCart::total() }}

Total Items
{{ LaraCart::count() }}
<br><br>
<form action="/cart/add">
    <button>Add Random Item</button>
</form>

<form action="/cart/fee">
    <button>Add $5.00 Delivery Fee</button>
</form>

<form action="/cart/destroy">
    <button>Destroy</button>
</form>
```

**Comment by christophe-44-27** [comment]
Ok, so it's nearly work, in fact, it's "LaraCart::getItems()" that doesn't work in my way.


This works (but the counter return 0)
`
//In AppServiceProvider
View::share('cart_items', LaraCart::count());

$items = LaraCart::get()->cart->items;
return view('customer.cart.cart', compact('items'));
`

This doesn't works
`
//In AppServiceProvider
View::share('cart_items', LaraCart::count());

$items = LaraCart::getItems();
return view('customer.cart.cart', compact('items'));
`

**Comment by lukepolo** [comment]
If you try to use share in the boot method its too early, and the cart has not been loaded yet. I you can manually load the cart though to make it work in a middleware :


```php
<?php

namespace App\Http\Middleware;

use Closure;
use LukePOLO\LaraCart\Facades\LaraCart;

class LoadCart
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        $cartItems = LaraCart::count();
        view()->share('cartItems', $cartItems);
        view()->share('totalItems', $cartItems);
        return $next($request);
    }
}

```

**Comment by christophe-44-27** [comment]
Oh ok ! Perfect, you're solution works :D thank you for your fast support ^^

**Comment by lukepolo** [comment]
No problem, i don't think that is the best solution, you should be able to do it after the cart has loaded. You may be able todo it in the register method rather than the boot method.

**Comment by lukepolo** [comment]
Or mabye use a view composer instead 

https://laravel.com/docs/master/views#view-composers
