### ISSUE TITLE
Install on Laravel 7

### ISSUE THREAD

**Issue by agbottan** [lukepolo/laracart#263]
Hi all.
I tried installing Laracart on Laravel 7 and got the following errors.
[composer-install-laracart-laravel7-error.txt](https://github.com/lukepolo/laracart/files/4296340/composer-install-laracart-laravel7-error.txt)
Is it because Laracart isn't yet working with the very recent Laravel 7 ?
Are there something that I can do?
Thank you.

**Comment by lukepolo** [comment]
Testing #264

**Comment by lukepolo** [comment]
Pushed out a new version 1.9.0 , currently does not support PHP 7.4 untill we fix #223

**Comment by agbottan** [comment]
@lukepolo , Thanks for fast and good response.
I did not know if this was the right way to address this question. I searched for a forum about Laracart and didn't found any, so I used this channel.

**Comment by lukepolo** [comment]
@agbottan here is perfect.  Feel free to post any issues or concerns here as well.
