### ISSUE TITLE
Problem with cart totals [PHP 7.3] 

### ISSUE THREAD

**Issue by spaceageliving** [lukepolo/laracart#269]
Hi Luke,

Been using this package for several years with much success.  Recently came back to the code and am having a few issues that I can't explain or diagnose.

I'm on L5.4, and have upgraded to "lukepolo/laracart": "1.6.*" in an attempt to get these issues resolved.

Only other thing that would have changed was composer updating to a new minor Laravel 5.4.x version and related deps.

All of the Cart Totals are returning "0.00" regardless of how many items are in the cart.  Other Cart operations, like getItems() and add() seem to be working.

For example, you can see here that the cart has two items in it, yet ::total() and ::subTotal() are returning "0.00":

<img width="481" alt="Screen Shot 2020-07-25 at 12 44 29 PM" src="https://user-images.githubusercontent.com/874600/88465071-c2ec0f80-ce74-11ea-8cc6-e7d0d6f8f083.png">

Also, in my views, I can no longer access props of CartItems.

For example, in a @foreach (LaraCart::getItems() as $item), I can't retrieve {{ $item->name }} any longer.  If I do {{ $item->options['name'] }} that works.

What am I missing here?

**Comment by lukepolo** [comment]
What PHP version are you using?

**Comment by spaceageliving** [comment]
7.3 in dev, but seeing similar issues with 7.1 in production.

**Comment by lukepolo** [comment]
I've seen similar issues with sessions and what not. 

Are you able to reproduce this in a clean laravel instance? 

Also post your middleware if you can here.

**Comment by spaceageliving** [comment]
Haven’t tried with clean install...I’m on vacation, back on Thursday.  I’ll send more info then.  Thanks for getting back.

**Comment by spaceageliving** [comment]
Hi Luke, I did a clean Laravel 5.4.* install.  I've tried lukepolo/laracart": "1.3.*" and lukepolo/laracart": "1.6.*" with same results.

I am on php 7.3.12 on dev system.  Doing some further digging around, from my controller I can:

dd(LaraCart::getItems())

and get the cart items successfully:

<img width="434" alt="Screen Shot 2020-08-03 at 3 01 09 PM" src="https://user-images.githubusercontent.com/874600/89231436-30e1b680-d59a-11ea-9c91-dc6c8b68e6aa.png">

but anything to do with math fails, for example:

dd(LaraCart::count());

returns 0

dd(LaraCart::total());

returns "0.00"

Middleware is web:

<img width="1209" alt="Screen Shot 2020-08-03 at 3 03 57 PM" src="https://user-images.githubusercontent.com/874600/89231661-9afa5b80-d59a-11ea-88b6-b92a9bb1de07.png">

I'm baffled by this...hopefully its a config thing or something?

**Comment by spaceageliving** [comment]
Here is a cart item with attributes showing:

<img width="448" alt="Screen Shot 2020-08-03 at 3 07 53 PM" src="https://user-images.githubusercontent.com/874600/89231909-296edd00-d59b-11ea-9fb9-98fce54ce6e2.png">

**Comment by lukepolo** [comment]
php 7.3 deprecated money function. You will need to use a higher laracart version that doesn't use it anymore.

**Comment by spaceageliving** [comment]
Ahhh ok....so I'm on php 7.3, Laravel 5.4

**Comment by spaceageliving** [comment]
Is there a min req for Laracart in this config?

**Comment by spaceageliving** [comment]
I moved my dev system back to 7.1 and everything is kosher.  It seems like there is an issue with php7.3.

**Comment by lukepolo** [comment]
If you need to use php 7.3 try with the latest 1.11.0
