### ISSUE TITLE
How to display total amount by different taxes

### ISSUE THREAD

**Issue by t-prod** [lukepolo/laracart#270]
Hi all,

I have several products with a different vat rate (10% and 20 %). How can we display it separatly to display amount group by taxes ?
Ex : 
Product A = VAT of 0.1 
Product B = VAT of 0.2

Total amount 10% : XXX
Total amount 20% : XXX 

Any solution ?

**Comment by lukepolo** [comment]
If you need to seperate them out like that, you could make different cart instances for each of the VAT's .

Otherwise you could re-create the total function and loop through your items and seperate the totals that way.

**Comment by t-prod** [comment]
Hi,

Thanks for your answer I figured it out by looping each items and calculate the tax by grouping tax by percent.
Thanks again for your answer ;)

Regards
