### ISSUE TITLE
addSubItem has no tax in tax calculation

### ISSUE THREAD

**Issue by dennisoderwald** [lukepolo/laracart#278]
As it seems I can't set a tax to an addSubItem but also the tax from the original item is not taken into account, so all sub items are calculated without tax.

```php
    $item = LaraCart::add(2, 'Product Name', 1, 1.00, [
        'tax' => '0.19'
    ]);

    $item->addSubItem([
        'price' => '1.00',
        'qty' => 1
    ]);
```

Expected result:

> Sub Total: 2.00
> Tax Total: 0.38
> Total: 2.38

Output result:

> Sub Total: 2.00
> Tax Total: 0.19
> Total: 2.19

The variables 'taxable' and 'tax' cannot be set in the sub-item either.

**Comment by dennisoderwald** [comment]
The problem probably occurs in connection with `tax_by_item` => true.

**Comment by lukepolo** [comment]
this has been fixed in the newer branch.
