### ISSUE TITLE
Sub items are rounded incorrectly

### ISSUE THREAD

**Issue by dennisoderwald** [lukepolo/laracart#281]
We usually work with 2 decimal places, but we have also tried it with 5 decimal places and it seems to ignore them.

```php
$product = Product::find(42);
$item = LaraCart::add($product);
$item->tax = $product->tax; // 19%

$item->addSubItem([
    'description' => 'First item',
    'price' => 8.40336,
    'qty' => 1
]);

$item->addSubItem([
    'description' => 'Second item',
    'price' => 4.20168,
    'qty' => 1
]);
```

Expected result:

> Netto (LaraCart::subTotal()): 12.61
> Tax Total (LaraCart::taxTotal()): 2.39
> Total (LaraCart::total()): 15.00

Output result:

> Netto (LaraCart::subTotal()): 12.60
> Tax Total (LaraCart::taxTotal()): 2.39
> Total (LaraCart::total()): 14.99

**Comment by lukepolo** [comment]
https://github.com/lukepolo/laracart/blob/b4592fae37e0da747f6f592bd3897fdc3a0c6fc4/src/LaraCart.php#L726

**Comment by lukepolo** [comment]
I dont have time at the moment to fix it , but will accept a PR

**Comment by dennisoderwald** [comment]
@lukepolo Okay, thank you. We'll take a look at that. But for info in the current state of the `master` branch 5 tests are failed. Are you aware of that?

**Comment by furkanyesil** [comment]
@lukepolo I have created a PR to solve this problem. PR #282. As @dennisoderwald mentioned, there are failing tests. The tests are in a file which has not changed for 14 months.

**Comment by lukepolo** [comment]
yah the test i broke with the last fix , ill need to fix those as well
