### ISSUE TITLE
Support Laravel ^8

### ISSUE THREAD

**Issue by Augen2203** [lukepolo/laracart#287]
hello, laravel 8.12 does not get up, will there be support? Thank you

**Comment by lukepolo** [comment]
Ill be working on laracart in the next couple of weeks, expect to see this working here soon.

**Comment by Augen2203** [comment]
Great, I'm really looking forward to a new update from you.
Thank

**Comment by Augen2203** [comment]
> Ill be working on laracart in the next couple of weeks, expect to see this working here soon.

Great, I'm really looking forward to a new update from you.
Thank

**Comment by lukepolo** [comment]
my new branch should solve this soon.
