### ISSUE TITLE
Laravel authentication stopped working after using this package (User get logout).

### ISSUE THREAD

**Issue by sajidbashir24h** [lukepolo/laracart#302]
Currently, i am using Laravel Framework 7.30.4 after using lukepolo/laracart 1.* package i am facing logout issue. User get authenticated but soon redirect back to login screen. It seems sessions get expired. If I remove this package then everything works fine. 
Can you please help how to handle this situation?

**Comment by sajidbashir24h** [comment]
The issue is resolved. It was not because of laracart package.  thanks

**Comment by sandervanh** [comment]
@sajidbashir24h What was your issue? Having the same issue right now.

Thanks!
