### ISSUE TITLE
PHP 8.0 your php version (8.0.9) does not satisfy that requirement.

### ISSUE THREAD

**Issue by pasamsin** [lukepolo/laracart#308]
Problem 1
    - Root composer.json requires lukepolo/laracart 1.11.* -> satisfiable by lukepolo/laracart[1.11.0].
    - lukepolo/laracart 1.11.0 requires php ~7.2 || ~7.3 || ~7.4 -> your php version (8.0.9) does not satisfy that requirement.

**Comment by lukepolo** [comment]
you will need to use 2+
