### ISSUE TITLE
error with composer

### ISSUE THREAD

**Issue by TerrePorter** [lukepolo/laracart#313]
I am trying to install the laracart package but receive an error about illuminate/support

 - lukepolo/laracart[1.4.0, ..., 1.4.6] require illuminate/support ^5.4.0 -> satisfiable by illuminate/support[v5.4.0, ..., 5.8.x-dev].
    - Only one of these can be installed: illuminate/support[v5.4.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v8.40.0, ..., 8.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^8.40 -> satisfiable by laravel/framework[v8.40.0, ..., 8.x-dev].
    - Root composer.json requires lukepolo/laracart 1.4.* -> satisfiable by lukepolo/laracart[1.4.0, ..., 1.4.6].

I don't have illuminate/support installed, but I see it as a requirement for laracart package. 

I don't know what to do to fix the project, but i would like to use the laracart

**Comment by lukepolo** [comment]
I think my doc site is out of date, which version of laravel are you trying to use? 

for 9 , use 2.2.0 instead of 1.4

**Comment by TerrePorter** [comment]
That worked nicely. Thanks

**Comment by lukepolo** [comment]
awesome, i updated the docs site too
