### ISSUE TITLE
Unable to apply several percentage coupons

### ISSUE THREAD

**Issue by t-prod** [lukepolo/laracart#314]
Hi,

I can apply several Percentage coupons on the cart (not on the item). 
Only one is supported despite the fact I have config('laracart.multiple_coupons') to true.
How can I achieve to have multiple coupons like this ?

```
$couponType = '\LukePOLO\LaraCart\Coupons\\'.$discount->getDiscountType();
$coupon = new $couponType($discount->code, $discount->discount_percent / 100, [
    'description' => $discount->code.' '.$discount->discount_percent.' %'
]);
LaraCart::addCoupon($coupon);
```
Thanks for your help

**Comment by t-prod** [comment]
OK the variable in config/laracart.php with 'multiple_coupons' => true, does not have effect.
The vendor\lukepolo\laracart\src\Cart.php use config helper but I think it's the package's config that it's in use rather than my config file.
Do you have a fix ?

**Comment by t-prod** [comment]
If I comment like this it's working :
![image](https://user-images.githubusercontent.com/1824638/191281081-8e602626-c9a0-4b56-809c-98085c6da333.png)

**Comment by lukepolo** [comment]
think it may be a config option

**Comment by t-prod** [comment]
It's the case in tour constuctor to get the config variable named multi_coupons. But this one is only from your package and not the config/laracart.php itself. Which solution could we have?

**Comment by t-prod** [comment]
Is there a way to set coupons to each items to make easier order lines with Eloquent?

**Comment by lukepolo** [comment]
looks like it was a bug #319
