### ISSUE TITLE
Manage promotion Buy x Get Y

### ISSUE THREAD

**Issue by aeq-dev** [lukepolo/laracart#317]
Hello,
I'm using this awesome package, thanks for it.
I'm trying to apply promotion concept, a customer may buy x products and get y products (free or discount).
How can I mange it ?

Example : 
Buy 2 products from category foo, you get 1 free product bar

Thanks :)

**Comment by aeq-dev** [comment]
I did it :) never mind

**Comment by diegonella** [comment]
please share howto
