### ISSUE TITLE
how to use laracart without login 

### ISSUE THREAD

**Issue by TarekRamadan91** [lukepolo/laracart#321]
dears ,,
I am currently implementing an e-commerce project and I need to use laracart, but I need that if the visitor is not logged in to the site, he can add the products to the cart and after logging in the order is completed. Is there a way to do this?

just save cart to session or db with unique id ,, thnx

**Comment by lukepolo** [comment]
i haven't touched laravel in a while, but yuo should be able to track the session across the login

**Comment by TarekRamadan91** [comment]
thnx for ur response ,,, i mean how to save cart to session with unique id

**Comment by lukepolo** [comment]
i think thats just built into laravels sessions 


$session_id = Session::getId();

**Comment by TarekRamadan91** [comment]
thnx for ur response ,,, i mean how to save cart to session with unique id 

> i think thats just built into laravels sessions

I guess I couldn't explain it enough, what I just want is use ur laracart without auth ? is there any way to do it ? ,, thnx :)

**Comment by lukepolo** [comment]
yah auth isn't required , are you having an issue without being authed?

**Comment by TarekRamadan91** [comment]
> yah auth isn't required , are you having an issue without being authed?

thnx ,, i don't have any issue with auth but when try to add item to cart without auth and make dd(LaraCart::getItems()); its return last item added only !!! but if try to add items with auth user its work good ,So I thought it should be authenticated

this is my code 

   ```
     public function laracart(){


            $item = \LaraCart::addline(623, 'Shirt', 1, 10, [
                'size' => 'm'
            ],
                $taxable = false
            );
            
            dd(\LaraCart::getItems());

}
```

**Comment by TarekRamadan91** [comment]
@lukepolo thnx ,, the issue from my side and now working fine :) ,, now i've other question if i can :) ,, how to add discount value to product without coupon?

**Comment by lukepolo** [comment]
i would just add a coupon , otherwise you could do item->price = 1312

**Comment by TarekRamadan91** [comment]
what if laracart take price from product model ??

**Comment by lukepolo** [comment]
you should be able to override it

**Comment by TarekRamadan91** [comment]
thanx ,, every thing oky now :)
