### ISSUE TITLE
adding products bug

### ISSUE THREAD

**Issue by dsfser** [lukepolo/laracart#49]
Hey there,

whenever i add a product it works for the first 3 times then the item hash changes.

after 3 times the print_r($this->getItem($itemHash)); does not return a value.

it can not find the item anymore (but still excists) and then adds a new row.

but after 3 times than he removes the second row (first row still excists) and than creates again another row...

very strage bug.

**Comment by lukepolo** [comment]
I'll fix this today . Can you supply exactly what item your adding ?

**Comment by dsfser** [comment]
Thanks,

I am adding: LaraCart::add(1, "test product", 1, 15.99);

Do you maybe have a clue where to look?

**Comment by dsfser** [comment]
i did some debugging:

This is the response of the third time added a product:

print_r($this->getItems());

    Array
    (
    [35edd624bfbf6d8c5511712656dbb10d] => LukePOLO\LaraCart\CartItem Object
        (
            [itemHash:protected] => 35edd624bfbf6d8c5511712656dbb10d
            [id] => 1
            [tax] => 0.21
            [name] => test product
            [code] => 
            [locale] => 
            [taxable] => 1
            [lineItem] => 
            [discount] => 0
            [subItems] => Array
                (
                )

            [couponInfo] => Array
                (
                )

            [internationalFormat] => 
            [options] => Array
                (
                    [qty] => 2
                    [price] => 15.99
                )

        )

    )
    okproduct added!

This is the response of the fourth time added a product:

print_r($this->getItems());

    Array
    (
    [3d838f162db431c36f58075de7f94a12] => LukePOLO\LaraCart\CartItem Object
        (
            [itemHash:protected] => 3d838f162db431c36f58075de7f94a12
            [id] => 1
            [tax] => 0.21
            [name] => test product
            [code] => 
            [locale] => 
            [taxable] => 1
            [lineItem] => 
            [discount] => 0
            [subItems] => Array
                (
                )

            [couponInfo] => Array
                (
                )

            [internationalFormat] => 
            [options] => Array
                (
                    [qty] => 3
                    [price] => 15.99
                )

        )

    )
    not so okproduct added!

This is the response of the fifth time added a product:

print_r($this->getItems());

    Array
    (
    [3d838f162db431c36f58075de7f94a12] => LukePOLO\LaraCart\CartItem Object
        (
            [itemHash:protected] => 3d838f162db431c36f58075de7f94a12
            [id] => 1
            [tax] => 0.21
            [name] => test product
            [code] => 
            [locale] => 
            [taxable] => 1
            [lineItem] => 
            [discount] => 0
            [subItems] => Array
                (
                )

            [couponInfo] => Array
                (
                )

            [internationalFormat] => 
            [options] => Array
                (
                    [qty] => 3
                    [price] => 15.99
                )

        )

    [35edd624bfbf6d8c5511712656dbb10d] => LukePOLO\LaraCart\CartItem Object
        (
            [itemHash:protected] => 35edd624bfbf6d8c5511712656dbb10d
            [id] => 1
            [tax] => 0.21
            [name] => test product
            [code] => 
            [locale] => 
            [taxable] => 1
            [lineItem] => 
            [discount] => 0
            [subItems] => Array
                (
                )

            [couponInfo] => Array
                (
                )

            [internationalFormat] => 
            [options] => Array
                (
                    [qty] => 1
                    [price] => 15.99
                )

        )

    )
    okproduct added!

the hash changes so the code cant find it anymore so it makes a new row...

**Comment by lukepolo** [comment]
Yup I see why, my code checks to see if there's an item of the same and increases the qty . But if we change the qty of course the hash will change and will not match any longer. I need to temporarily remove the qty while generating the hashes for it to work

**Comment by dsfser** [comment]
ahhh got it haha, i think its better to exclude the options array.

**Comment by lukepolo** [comment]
#51
