### ISSUE TITLE
subTotal ability to manage formatMoney on your own

### ISSUE THREAD

**Issue by Cannonb4ll** [lukepolo/laracart#54]
Hello,

I've noticed that whenever you call Cart::subTotal(); it would output like 'Eu 5,00'

Is it possible to disable this? I want to have control of this myself and not have the plugin do it for me. I do not need 'Eu' in front of it.

**Comment by Cannonb4ll** [comment]
Nevermind, I saw that the documentation is lacking options.

The documentation above stated:

```LaraCart::subTotal($tax = false, $formatted = true);```

**Comment by lukepolo** [comment]
Ill add it to the docs!
