### ISSUE TITLE
getPrice() vs getSubtotal()

### ISSUE THREAD

**Issue by bmartus** [lukepolo/laracart#55]
Hey Luke, starting to use this on a project.  I had a question and wasn't sure the best place to ask, let me know if you'd prefer these elsewhere.

Should getPrice() be the line item price and getSubtotal() be price*qty on the CartItem class?  Or am I missing how I'd get the unit price to display somewhere (besides just $line->price, which isn't formatted).

**Comment by lukepolo** [comment]
Awesome to hear your using LaraCart.

You making a compelling point, i will have to think on it. The reason why getPrice has qty and tax its just for the item it self without the sub options (... yah after saying it out loud it doesn't make sense)

I will see how I can change that tomorrow morning 

Thanks for the suggestion

**Comment by bmartus** [comment]
Maybe rename getPrice to getUnitPrice or add that method?

**Comment by lukepolo** [comment]
What do you think ? 

https://github.com/lukepolo/laracart/pull/57

**Comment by lukepolo** [comment]
Closed via #57
