### ISSUE TITLE
How to get itemHash?

### ISSUE THREAD

**Issue by Cannonb4ll** [lukepolo/laracart#56]
Whenever I do like this:

    $item = LaraCart::add(1, 'Burger', 5, 2.00, [
        // Notice this is an array of arrays,
        // this allows us to further expand the cart functions to the options
        [
            'Description' => 'Bacon',
            'Price' => 1.00
        ]
    ]);

And I dump the $item, I see a itemHash, but how do I get this hash? $item->itemHash; returns null.

I would like to add an item to my cart and afterwards add a option to this item if a certain condition is met.

**Comment by lukepolo** [comment]
I'll make it throw an exception but do getHash()

**Comment by lukepolo** [comment]
https://github.com/lukepolo/laracart/commit/a09f2b3c85c6910b6fc787f533c2bf34ca5ca3cc

**Comment by lukepolo** [comment]
This should work now , ill update the package after i fix this other issue

**Comment by lukepolo** [comment]
Updated, let me know if you have any other suggestions
