### ISSUE TITLE
[Question] Multilingual feature?

### ISSUE THREAD

**Issue by mosid** [lukepolo/laracart#62]
Is multiple languages supported?
like items name for example
I think it is a must nowadays
if not, i recommend checking one of these repos
- https://github.com/vinkla/translator
- https://github.com/dimsav/laravel-translatable  

Great work by the way..

**Comment by lukepolo** [comment]
That would be interesting to have baked in, if I get more requests for this I can spend some time into this. Working on some other features right now such as attaching users to the cart so they can login from a different device.

**Comment by lukepolo** [comment]
Ill look deeper into this. Thanks again for the suggestion.

**Comment by lukepolo** [comment]
I think this really falls out of the realm of the package. if others protest that they want this feature ill think about it again.
