### ISSUE TITLE
[Question] Product Weight?

### ISSUE THREAD

**Issue by bmartus** [lukepolo/laracart#63]
Any thoughts on tracking the weight of each item in the cart? At some point during checkout, shipping rates based on product weight and dimensions will need to be calculated.

weight (float)
length (float)
width (float)
height (float)
weight_uom (predefined set of UOMs?)
dimension_uom (predefined set of UOMs?)

**Comment by lukepolo** [comment]
This would be pretty cool, 

My thought would to make another file and call it CartShipping (...maybe) , i assume there is a service that you use for an external api call to determine the costs. 

But going back to the weight stuff we could make a CartShipping object that allows you to insert those attributes. So when you would call $cartItem->getShippingCost() it would fetch everything for you.

What are your thoughts?

**Comment by lukepolo** [comment]
I will be putting this in btw, i need this feature soon too :-)

**Comment by bmartus** [comment]
Was playing around with [EasyPost](https://www.easypost.com/) last night, integrates with a ton of shippers doing labels, tracking, address validation, etc. Found an old laravel 4 [service provider](https://github.com/mandofever78/laravel-easypost/) for it last night, submitted a [PR](https://github.com/mandofever78/laravel-easypost/pull/1) to update it to 5.2.

**Comment by lukepolo** [comment]
I probably wont have it connect to any certain package. But find a way to allow users to add any service. Without it being required by LaraCart

**Comment by bmartus** [comment]
Yeah, as long as the overall product data those packages needs (weight, dims, value) is readily accessible you should be fine.

**Comment by lukepolo** [comment]
More I thought about this , you can already do this. You could make your own function to add it onto it for ease of use but really im not sure if this falls into this package. Thoughts?

**Comment by bmartus** [comment]
I had the same thought.  Product attributes and a function on the checkout
process could handle this.

**Comment by lukepolo** [comment]
Going to close this.
