### ISSUE TITLE
Adding a model as option

### ISSUE THREAD

**Issue by Cannonb4ll** [lukepolo/laracart#70]
Hi,

I would like to add a complete model record from my database, as following:

    Cart::add(2, 'Product', 1, 20.00, [
       'model' => $product
    ]);

Getting an error like this:

     Exception in LaraCartServiceProvider.php line 48:
     Failed calling App\Models\Auction::jsonSerialize()

**Comment by lukepolo** [comment]
You will have to turn the model into an array $product->toArray()

**Comment by Cannonb4ll** [comment]
Ah thanks, but wouldn't it be nice to be able to do this so you can actually query on models inside afterwards?

**Comment by lukepolo** [comment]
Yes it would be :+1: .

I will look to add this feature this weekend!

**Comment by lukepolo** [comment]
https://github.com/lukepolo/laracart/tree/coupon_taxation#item-model-relations

On my other tree. but has some breaking changes. Will release as 1.1.0

**Comment by lukepolo** [comment]
#72  added in this PR

**Comment by FubuBy** [comment]
@lukepolo  https://github.com/lukepolo/laracart/tree/coupon_taxation#item-model-relations return 404

**Comment by lukepolo** [comment]
Use laracart.lukepolo.com for docs
