### ISSUE TITLE
Add item using model

### ISSUE THREAD

**Issue by spaceageliving** [lukepolo/laracart#95]
Would be cool if you could add products to the Cart based on an id/sku found in the item_model.  This way, instead of passing a bunch of params, an item can be added with a single param, eg.

LaraCart::add('my-item-sku');

If the item_model has cols assigned with appropriate names pertaining to the cart params, then values are inserted from the found item_model.

Maybe this is possible already?  I am just getting started with this, thanks for your efforts!

**Comment by spaceageliving** [comment]
Meant to say something like:

LaraCart::addItem('my-item-sku');

;)

**Comment by lukepolo** [comment]
That would be awesome, I will be adding this very soon.

**Comment by lukepolo** [comment]
#104

**Comment by lukepolo** [comment]
Your feature has be implemented :+1:
