### ISSUE TITLE
Freeshipping Coupon

### ISSUE THREAD

**Issue by spaceageliving** [lukepolo/laracart#97]
Additional coupon to offer free shipping for cart...not sure how this would integrate within context of how coupons are implemented currently, but get this from clients all the time.

**Comment by lukepolo** [comment]
How I would do it (with whats currently in the code) . Add shipping as a fee. And when the coupon is applied remove the fee.

**Comment by lukepolo** [comment]
Im going to leave this open, as I want to take some time to think if there is an easy way to add shipping costs in. 

Currently, everyone probably has their own method of defining how much it costs to ship. Regardless if it is a API service, or a constant you will be extending the shipping function to determine the cost. 

So the real question becomes, does it belong in LaraCart.


Let me know of your thoughts.

**Comment by lukepolo** [comment]
I may add the ability to add fees to items as well, for things like shipping cost, rather than have it set globally at the cart level

**Comment by bmartus** [comment]
With LaraCart being a cart and not an entire checkout solution, I would
think shipping costs calculation would be outside the scope of LaraCart.
But, adding the ability to set and store shipping cost (pre-calculated via
API or fixed amount) on the line level, and/or overall, is probably not a
bad idea.

But like you said above, you could just use the options or attributes on
the line and cart level to accomplish this.

On Thu, Mar 10, 2016 at 3:23 PM, Luke Policinski <notifications@github.com>
wrote:

> I may add the ability to add fees to items as well, for things like
> shipping cost, rather than have it set globally at the cart level
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lukepolo/laracart/issues/97#issuecomment-194902833>.
>



-- 
Brandon Martus
586-707-7078

**Comment by lukepolo** [comment]
Yah ill probably do that. Also I have a really cool feature coming out probably this weekend. It relates to #95 , should save you from writing extra lines of code (hopefully)

**Comment by lukepolo** [comment]
Closing, determined not to be part of this solution
