### ISSUE TITLE
Is the Sesssion Type Database?

### ISSUE THREAD

**Issue by masterpowers** [lukepolo/laracart#98]
I see your adding a cart_session_id in the users table,
is there an option to use other session driver?
if none , is it possible to use the sessions table and add the column there...
looking for ur feedback thanks

**Comment by lukepolo** [comment]
You need some unique identifiable information to share another session. Thats the reason why i put it on the users table. 

The feature that your talking about is for cross browser using the users table. 

As for the cart , there is no other types of storage available at this time. But would like to create migrations for people that want to use the type of database.

**Comment by masterpowers** [comment]
would love to make it work on redis or memcached..but more preferable redis

**Comment by lukepolo** [comment]
It does, it works based on what your session type is your laravel session
config

**Comment by lukepolo** [comment]
Closing issue. Will create issue to create a database version .
