### ISSUE TITLE
How to access itemHash?

### ISSUE THREAD

**Issue by didadan** [lukepolo/laracart#99]
Hi Lukepolo,

we want to delete an item and check first if we have it. Therefor the code:

    $matches = \LaraCart::find(['id' => $item_id, 'name' => $name]);

    // if we found the item
    if(count($matches) > 0){
        // remove item and return current cart
        \LaraCart::removeItem($matches->getHash());
        return 'success';
    }

This won't work because there is no such function on the array. How to I get the itemHash in this case? Would you suggest another approach?

Thank you.

**Comment by lukepolo** [comment]
So the matches will return the items, so basically instead do 

foreach($matches as $item) {
 \LaraCart::removeItem($item->getHash()));
}

**Comment by lukepolo** [comment]
Infact you can remove the count entirely cause it will be an array and the foreach will take care of that.

**Comment by didadan** [comment]
Great, I didn't know that there can be a function on an individual array value.
Thank you for the quick reply.
